### ISSUE TITLE
如何排查webpack打包产物大的问题？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#1]
## 问题描述

在`DEV`环境开发时，发现`webpack`打包用时很长，打包产物大，如何定位并解决这个问题，请说出详细步骤

## 最佳答案

[XeryYue的回答](https://github.com/BetaSu/fe-hunter/issues/1#issuecomment-1074746441)

## 答题同学须知

最佳答案由`围观同学`的`👍`和[卡颂](https://github.com/BetaSu)共同决定。**非答题相关评论**会被删除，问题相关内容讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)里讨论

## 围观同学须知

对于你满意的答案，请不要吝惜你的`👍`，这是评选**最佳答案**的标准

**Comment by BetaSu** [comment]
hello

**Comment by croatialu** [comment]
使用插件：
[webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer )

通过插件来分析引用的各个第三方包体积大小， 将一些非必要构建进去的第三方包通过 `external` 抽离出去， 以cdn 的方式引入项目，如 lodash， dayjs，qs， 等这种纯的js库 。（避免了对这些包的构建）

**Comment by OrangeSAM** [comment]
接楼上回答，如果是vue-cli构建的项目，已经集成了这个插件，可以直接使用命令 `vue-cli-service build --report` 输出包大小分析报告。
但题目要中是DEV环境，按理也是一样的。

**Comment by yaogengzhu** [comment]
打包用时很长 
- 可以结合使用 exclude ，来避免重复打包
- 配合 使用 thread-loader 多线程打包
- 以及webpack5.x 中提到的持久缓存属性，可以加快第二次打包速度

**Comment by 0753Lar** [comment]
打包用时长：换vite
打包体积大：webpack-bundle-analyzer

**Comment by jerry-lllman** [comment]
1. 在 npm build 时，一般终端都会将打包前后的大小给出来，对于不同的大小都会给出不同的颜色，一般上来黄色就是算大的了
2. 使用 webpack-bundle-analyze 进行可视化分析，文件越大所占的空间越大，可针对这写占用较大的文件进行优化
3. 使用 webpack -> chainWebpack -> optimization 进行代码压缩及使用其 splitChunks 进行分包处理。同时还可以针对 node_modules 下的包做 exclude
4. 对于较大的npm依赖包，可以考虑使用script cdn的方式引入，从而减少包体积
5. 项目中可能存在大量图片，对于这些图片同样适用cdn的方式，不将其打包至项目包中

**Comment by shenzhim** [comment]
webpack的打包优化，主要就是围绕“又快又小”的目标进行，在dev环境和正式环境 追求的目标不一致，有一些配置也会不同。这里简单说几点平时会有到的一些方案：
1. thread-loader 多线程提高loader的处理时间，cache-loader 加快二次打包速度
2. 使用合适的source-map 策略（dev环境，需要详细的错误定位，开发环境，则可以选择不要sourcemap，或者分离sourcemap文件，具体策略可参看官网说明）
3. 针对打包文件大的问题，可使用analyzer插件进行分析，通过extreals，include，exclude等配置进行不必要的打包
4. 同样针对bundle过大时，考虑使用code splitting方式，对代码进行异步加载import()，以及Optimization.splitChunks中配置合理的cachegroup
5. 另外顺带说句，在正式环境中使用webpack自带的压缩或者第三方压缩插件和gzip插件也是必要的

**Comment by nonzzz** [comment]
先说过程为什么bundle会很大,在开发项目的时候业务的叠加导致bunle大的必然的

### css部分

首先我们以css文件举例,重复的`style`导致build的时候这些无意义的体积激增,这也就是为什么在现在`css in js` 原子化火的理由, 采用`css in js`或者原子化`css`可以减少部分体积.

### 静态资源部分

我们或多或少在项目中引入静态文件资源我们以图标icon举例,不是所有文件都需要打包成`base64`,我们可以根据需要对这些文件进行处理

### 代码部分

业务的拓展包括包的引入，无一例外会增加我们的包体积,对于这些`bundle`工具而言,有`tree-shaking`和`DEC`，但是我们无法确保我们使用的包是否可以支持`tree-shaking`,所以在面对一些无法`tree-shaking`的包我们可以使用`antd`的`babel-import`插件去做死码消除。在编写一些代码的时候我们应该明确指明是否有副作用合理的给代码加上`@pure` 进行标记。拥抱esm的开发方式让这些`bunle`工具更好的工作，同时在工程上设置`sideEffect`保证我们能充分的享受到`tree-shaking`。


答完了编码部分在源头解决了一些问题后，我们再来思考下在build完他还是那么大该怎么解决。

- 合理的切割code,部分模块设置为`external` 防止被打包到`bundle`中,然后发布的过程采用`cdn`进行替换。
- 使用`webpack-analyze`或者`rollup-analyze` 分析工具分析具体chunk 和module。根据业务需要进行优化改造,
- 合理思考目前应用的服务群体,到底是兼容到多少版本,这样你才能控制你的`babel`或者`swc`需要`transform`的版本。
- 关于`@babel/core`和`@babel/runtime-hepler`等包的依赖 ,你应该明确清楚你要如何使用,使用不当导致的体积变大也不是没有。
- 使用`treser`或者`esbuild`等压缩工具进行代码压缩
- 关于`source-map`在生产环境下你可以关掉这样也会减少体积


### Dev 模式下

- 如果业务不是强依赖于`webpack`相关，可以考虑在`dev`模式下使用`vite`，根据现有`webpack`架构设计,根本无法和`vite`相比，因为两者的工作原理不同，导致了在dev环境下差异明显,
- 如果你强依赖于`webpack`那么你需要增量编译合理利用缓存,其次对于`require.context`这样的东西应该避免使用,
- 然后`ts-loader`这些你完全可以使用`thread-loader`去替代他们，记住多线程构建并不是良药,进程的开销是需要代价的,你应该在本地测试得出我到底需不需要启动多进程以达到最好的效果。
- 关于`source-map`，选择合理的配置模式
- 在开发环境下我们或许不需要`babel`转换到兼容更低的版本。


我希望各位熟知奥卡姆剃刀法则( 如无必要，勿增实体) 这样你才能在根源上解决问题

**Comment by nonzzz** [comment]
> 先说过程为什么bundle会很大,在开发项目的时候业务的叠加导致bunle大的必然的
> 
> ### css部分
> 首先我们以css文件举例,重复的`style`导致build的时候这些无意义的体积激增,这也就是为什么在现在`css in js` 原子化火的理由, 采用`css in js`或者原子化`css`可以减少部分体积.
> 
> ### 静态资源部分
> 我们或多或少在项目中引入静态文件资源我们以图标icon举例,不是所有文件都需要打包成`base64`,我们可以根据需要对这些文件进行处理
> 
> ### 代码部分
> 业务的拓展包括包的引入，无一例外会增加我们的包体积,对于这些`bundle`工具而言,有`tree-shaking`和`DEC`，但是我们无法确保我们使用的包是否可以支持`tree-shaking`,所以在面对一些无法`tree-shaking`的包我们可以使用`antd`的`babel-import`插件去做死码消除。在编写一些代码的时候我们应该明确指明是否有副作用合理的给代码加上`@pure` 进行标记。拥抱esm的开发方式让这些`bunle`工具更好的工作，同时在工程上设置`sideEffect`保证我们能充分的享受到`tree-shaking`。
> 
> 答完了编码部分在源头解决了一些问题后，我们再来思考下在build完他还是那么大该怎么解决。
> 
> * 合理的切割code,部分模块设置为`external` 防止被打包到`bundle`中,然后发布的过程采用`cdn`进行替换。
> * 使用`webpack-analyze`或者`rollup-analyze` 分析工具分析具体chunk 和module。根据业务需要进行优化改造,
> * 合理思考目前应用的服务群体,到底是兼容到多少版本,这样你才能控制你的`babel`或者`swc`需要`transform`的版本。
> * 关于`@babel/core`和`@babel/runtime-hepler`等包的依赖 ,你应该明确清楚你要如何使用,使用不当导致的体积变大也不是没有。
> * 使用`treser`或者`esbuild`等压缩工具进行代码压缩
> * 关于`source-map`在生产环境下你可以关掉这样也会减少体积

这里额外补充，关于前面的人回答的gzip等压缩模式，按照我个人的理解,gzip这些属于服务于业务而不属于`bundle`的范畴。它只能算工程化优化的一环和`webpack`等bundle工具是无关的

**Comment by bunney** [comment]
补充和实践帖
包体积分析这肯定是第一步要做的，但是要关注哪一部分
1. 大包
2. 复用包
3. 冗余包
如何做？

1. 大包如何处理 常见的很多 `lodash `都没做优化 ，可以用` lodash-es` 或者` babel-loadsh-xx` 转为 `esm `引用 `tree-shaking` 就能处理了亦或是一些三方包 这里只举例 类似于 moment 的语言包 还有highlight.js 类似的业务包 都可以做一些语言包的去除，UI库一般官方都提供对应的 `babel-import` 配置。业务代码的话就是组件拆包 解决单包体积过大。库依赖也可以做 `cdn `不参与构建。
2. 复用包 一般情况下 在`analyze `的 `report `中很容易发现复用模块，如果 dll 打包模式 要做合理的公共依赖抽离再配合`CodeSpliting `做合理拆包。不是话就基于`webpack5x `直接做拆包 完全可以替代 dll。
3.  冗余包就看对业务代码层面理解了，我的理解就是些无关紧要的包能自己实现就实现 不要过度依赖三方包。随着时间积累，一样能沉淀出符合自己业务线的工具包且可控

整体体积优化 
代码压缩  简单的可选方案  
1. `webpack optimization` 配合 `terser` 
2. `swc`
3. `esbuild`
这三种都有压缩方案 且 体积 速度 各有优劣 自己取舍

**Comment by fulvaz** [comment]
首先找到为什么体积大。webpack-bundle-analyzer 或者其他工具其实都能够很好地分析出问题点。
优化包体积的本质是优化 ttu 和 ttv。使用 webpack 的工具进行优化只能优化出普通的水平，如何业界领先需要对业务的深入理解，目标是：哪些 module 是首屏不需要的。

为了达到这个目的，需要得到以下信息：
1. 定义你的 TTV 和 TTU；
2. 打开 performance 分析首屏做了什么，特别是注意观察哪些 chunk 是 TTV 和 TTU 必须的。

回到 webpack-bundle-analyzer 里观察这些 chunk 的组成，观察哪些 module 是可以移除的。

现在找到了可以被移除的 module，那怎么移除呢？

要解决这个问题，你需要知道一个 module 为什么被引入了。

在一些巨型项目里一个 module可能同时被 3~4 个module引用，这些module分布在不同的 chunk 里，这些 chunk 有可能是首屏 chunk（需要移除），有些是非首屏chunk（不需要移除），哦吼， 怎么去分析呢？

好像社区里没这个解决方案，但你在使用 webpack-bundle-analyzer 前会有一个 stat.json，stat.json里有所有 module 的引用关系。

有这个关系就简单了，只要解除 module 对首屏 chunk 的引用即可。

接触的方法就是将 module 改成 loadable + 延迟初始化该 module。

至于延迟初始化的实现方法也有很多，和这个问题无关，我就不写了~ happy hacking。
