### ISSUE TITLE
如何准备述职报告？

### ISSUE THREAD

**Issue by Geekhyt** [BetaSu/fe-hunter#16]
### 发生问题的场景

小明是个职场新人，下个月准备做述职报告，他很紧张。。。你能从以下几点给他建议么？

### 需要解决的问题

请从以下顺序回答该问题：

1. 述职报告应该围绕哪些点展开？
2. 有哪些需要注意的可能的坑点？
3. 如何演讲才能展现自己真正的实力，让评委印象深刻？

## 最佳答案

[eyea的回答](https://github.com/BetaSu/fe-hunter/issues/16#issuecomment-1078750935)

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是当日18：00左右评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by Wcdaren** [comment]
PPT：https://slides.com/wcdaren/deck-1fa0df/fullscreen
演讲稿：[转正述职.pdf](https://github.com/BetaSu/fe-hunter/files/8346868/default.pdf)
## 述职报告应该围绕哪些点展开？
详情请看PPT
## 有哪些需要注意的可能的坑点？
我们当时是总监+组长+HR ，所以讲的时候尽量考虑一下HR，意思就是不要讲太技术的
大概展现自己解决问题的能力和发展潜力
## 如何演讲才能展现自己真正的实力，让评委印象深刻？
不要念稿。因为我用的是slides，本来就没那种PPT备注可以念稿。所以都是随性讲的。
如果是PPT的那种有备注的，念稿的体验会挺差的
反正都是走形式的述职，就当成是分享互动就好了

>如果只有我一个人回答，麻烦把赏金加到100 哈哈哈

**Comment by eyea** [comment]
#### 一、述职报告应该围绕哪些点展开？

1. `复盘` 个人对阶段工作的回顾和总结，从过去一段时间工作的成败得失，好的经验，在未来的工作中继续保持，失败的教训在未来的工作中想办法避免。

2. `展示` 工作成果的展示，阶段性的成果，要突出对中心整体目标的贡献、和公司业务目标之间的关联性。专业能力的展示，要突出达成目标的过程有什么样的挑战，自己是怎么解决的，解决方案的优缺点是什么。思考能力的展示，持续迭代自我进化的能力，当前项目的后续优化方向是什么，PDCA，Check和Action的能力差异是两个人发展速度差异的根源，举一反三的能力，从已有的项目里能衍生出哪些事情。

3. `校正` 通过述职发现问题，比如目标是否和公司大目标对齐、解决方案是否有优化的空间、和兄弟团队的协作是否可以做的更好等。越充分的暴露问题，越有机会及时的校正问题，及时回到正确的轨道上，所以，述职不要怕暴露问题。


####  二、有哪些需要注意的可能的坑点？

1. 针对内容上，`复盘`的面向自己的，`展示`是面向所有人的，`校正`是面向上级的，一个好的述职应该能对上述三个问题都有很好的解答。切忌把述职写成流水账，变成工作的罗列，没有总结、没有反思、没有行动计划。

2. 对于个人技巧上，可能会出现紧张手掌出汗、大脑空白思路短线、口干舌燥、情绪亢奋的情况

####  三、如何演讲才能展现自己真正的实力，让评委印象深刻？

1. 个人是比较看中内容以及表达，即便当事人表达有瑕疵，我也可以通过精心准备的ppt内容去感知这个同学的做事态度；如果表达OK，那更完美。

2. 其次，经验不是很多的同学要提前去练习，约个会议室、找个小黑板，拉上领导或者自己去模拟；录音去听，去反思自己这个过程有哪些好坏点。

3. 再者，上台就不要有刻意去讨好台下的谁谁谁的心态，此时做好自己输出表达，表达清晰，逻辑完整，也是一种难能可贵的人才。

**Comment by handsomeCarl** [comment]
**述职报告应该围绕哪些点展开？**

1. 思想（证明你的能力达到了目标级别的要求） + 论证（你达到目标级别的论据）
2.论据要挑选符合你级别要求的事情进行论证（分为 论证的背景，你负责的任务，你做了什么，给团队业务带来了什么好的结果）

**有哪些需要注意的可能的坑点？**

1.ppt能容不是越多越好，不是越炫酷越好，不是越详细越好，展示自己能力就好，更多是口述
2.答辩时候不要急于回答，听懂后再答
3.如果不知道的，诚实就好，想办法回到熟悉的领域
4.不要太过纠结一个问题


**如何演讲才能展现自己真正的实力，让评委印象深刻？**
1.按照有效页数量控制时间
2.ppt 要突出重点，精简，不要念ppt
3.提前模拟
4结果要量化，最好有指标数据、和之前的业务进行对比
5.晋升展示的是你的能力，不是业绩，你要重点突出自己能力

**Comment by alileew** [comment]
主流程：
1. 先梳理入职后做的所有项目（不管大小）全部罗列并简单梳理一遍
2. 二次梳理项目中你觉得有含金量、有难点的项目或组件（推荐：用思维导图 xmind进行梳理），并能说明白自己做的业务的来龙去脉，不要只是为了写代码而写代码 （建议：如果业务不清楚，一定要去问你的领导，某块项目的业务是什么样的场景）
3. 然后再度梳理并挑出 3~4 个你觉得你做过的最能证明你能力的项目，把重点（推荐：数据量化。如 页面提升了多少秒、封装的通用模块支撑了多少页面、所做的业务为其他业务做了多少的赋能.....）全部用数据化的形式提炼出来
4. 通过STAR法则进行述职 - 重点：「结论先行」（推荐阅读：[金字塔原理](https://zhuanlan.zhihu.com/p/403255484)）

需要注意的点：
1. 自我阐述控制在15 ~ 20分钟（平时自己在家掐表进行练习，或者说给自己的朋友、爱人听）
2. PPT要简洁，不要放满满的字。PPT只起到提示的作用，主要靠嘴输出讲给评委听，而不是对着PPT一个个字的读给评委听
3. 语速不要过快，不然评委PPT还没看清楚，你PPT已经翻到下一页了
4. 一定要表现出自信，拍着胸脯说，这就是我做的东西，不要说话很害羞，让人觉得东西好像不是你做的一样
5. 除了硬技能，述职PPT上尽量表现出一些 软技能。如：帮助组内同学成长或作为mentor辅导新人、经常分享高质量技术沉淀、经常组织code review、经常backup组内同学处理开发问题等等.....

**Comment by tunshiyu** [comment]
首先混成嫡系
