### ISSUE TITLE
实现 add(1)(2)(3)(4) = 10

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#2]
## 问题描述

实现**add**函数，使得：

`add(1)(2)(3)(4)`输出结果为**10**

`add(1)(2)(3)`输出结果为**6**

请给出满足**普遍条件**的答案，写出你的实现思路和完整代码

## 最佳答案

[chanchunlei的回答](https://github.com/BetaSu/fe-hunter/issues/2#issuecomment-1074694344)

## 答题同学须知

最佳答案由`围观同学`的`👍`和[卡颂](https://github.com/BetaSu)共同决定。**非答题相关评论**会被删除，问题相关内容讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)里讨论

## 围观同学须知

对于你满意的答案，请不要吝惜你的`👍`，这是评选**最佳答案**的标准，**非答题相关评论**会被删除

**Comment by wanlum** [comment]
const add = x => y => z => w => x + y + z+ w;

**Comment by chanchunlei** [comment]
```js
function add() {
	const _args = [...arguments];
	function fn() {
		_args.push(...arguments);
		return fn;
	}
	fn.valueOf = function() {
		return _args.reduce((sum, cur) => sum + cur);
	}
	return fn;
}
add(1)(2)(3)(4).valueOf();
add(1)(1,2,3)(2).valueOf();
```

当变量对象（函数也是对象）遇到一些情况的时候，会偷偷地调用 toString 和 valueOf 方法（隐式调用），那我们就可以改写这两个方法做一些事。

**Comment by c0dedance** [comment]
函数柯里化：==只传递给函数一部分参数来调用它，让它返回一个函数去处理剩余的参数==

`const add = x => y => z => w => x + y + z+ w`

会但来晚hhhh，我也来答答

**Comment by GuanyuChen** [comment]
```
function add(...params) {
	const func = add.bind(null, ...params);
	func.toString = () => params.reduce((prev, cur) => (prev += cur), 0);
	return func;
}
```

思路：利用 bind 保存链式调用的参数，利用 == 会隐式转换，调用 toString 方法

**Comment by 0753Lar** [comment]
赏金猎人来了： window.add=()=>()=>()=>()=>10

**Comment by yusonghuilife** [comment]
非开放性讨论价值不大

**Comment by jerry-lllman** [comment]
function add(x1) {
		let sum = x1
		function fun(x2) {
			sum += x2
			return fun
		}
		fun.toString = function () {
			return sum
		}
		fun.valueOf = function () {
			return sum
		}
		return fun
	}

	alert(add(1)(2)(3)(4))
	console.log(+add(1)(2)(3)(4)) // 利用 valueOf
	document.write(add(1)(2)(3)(4))

**Comment by heruifeng1** [comment]
> 赏金猎人来了： window.add=()=>()=>()=>()=>10

这个答案:用最轻量的成本 实现了 用户的需求......我们程序员也没有机会和 出题人 再次讨论需求, 那么这样写最好

**Comment by Kate605690919** [comment]
```
const add = function(num1, num2) {
  return num1 + num2;
}
function curry(add, n) {
  let count = 0;
  let arr = [];   
  return function reply(arg) {
    arr.push(arg);
    if ( ++count >= n) {
      return arr.reduce(function(p, c) {
          return p = add(p, c);
      }, 0) 
    } else {
      return reply;
    }
  }
}
// 需要几个参数n就写几
const sum = curry(add, 4);

sum(4)(3)(2)(1)  // 10
```

**Comment by yuehaocc** [comment]
> const add = x => y => z => w => x + y + z+ w;

问题更新了，这个答案直接gg，赞数虽然最高，但是并不完美

**Comment by qiang-chen** [comment]
function add(params) {
  return currying => params + currying;
}

**Comment by aniu2016** [comment]
```

function addProxy() {
  let sum = [...arguments].reduce((prev, cur) => prev + cur, 0)
  const proxy = new Proxy(function a() {}, {
    get() {
      return () => sum
    },
    apply(...args) {
      const val = args[2].reduce((prev, cur) => prev + cur, 0)
      sum += val
      return proxy
    }
  })
  return proxy
}
```

**Comment by cz160** [comment]
我测试好像不会主动调用toString方法,算违背题目了吧。。
// 实现 add(1)(2)(3)(4) = 10
const add = function (a) {
  let sum = a;
  function _add(b) {
    sum = sum + b;
    return _add;
  }
  _add.toString = function () {
    return sum;
  };
  return _add;
};
console.log(add(1)(2)(3)(4).toString());

**Comment by cz160** [comment]
测试好像不会主动调用toString方法，算违背题目了吧。。
`// 实现 add(1)(2)(3)(4) = 10
const add = function (a) {
  let sum = a;
  function _add(b) {
    sum = sum + b;
    return _add;
  }
  _add.toString = function () {
    return sum;
  };
  return _add;
};
console.log(add(1)(2)(3)(4).toString());
`

**Comment by cz160** [comment]
测试好像不会主动调用toString方法，算违背题目了吧
`
const add = function (a) {
  let sum = a;
  function _add(b) {
    sum = sum + b;
    return _add;
  }
  _add.toString = function () {
    return sum;
  };
  return _add;
};
console.log(add(1)(2)(3)(4).toString());
`

**Comment by cz160** [comment]
测试好像不会主动调用toString方法，算违背题目了
```js
const add = function (a) {
  let sum = a;
  function _add(b) {
    sum = sum + b;
    return _add;
  }
  _add.toString = function () {
    return sum;
  };
  return _add;
};
console.log(add(1)(2)(3)(4).toString());
```

**Comment by jialong5566** [comment]
function add(n){
  let sum = 0;
  let count = 3;
  sum += n;
  return count ? _add : sum;
  function _add(n){
    sum += n; 
    count--;
    return count ? _add : sum;
  }
}

**Comment by cz160** [comment]
收到，谢谢

**Comment by jialong5566** [comment]
function add(n){
      let sum = 0;
      let count = 3;
      sum += n;
      return count ? _add : sum;
      function _add(n){
            sum += n; 
            count--;
            return count ? _add : sum;
      }
}

**Comment by pan463859** [comment]
> 

可以展开说说哪些情况会调用 valueOf 吗？

**Comment by pan463859** [comment]
> ```js
> function add() {
> 	const _args = [...arguments];
> 	function fn() {
> 		_args.push(...arguments);
> 		return fn;
> 	}
> 	fn.valueOf = function() {
> 		return _args.reduce((sum, cur) => sum + cur);
> 	}
> 	return fn;
> }
> add(1)(2)(3)(4).valueOf();
> add(1)(1,2,3)(2).valueOf();
> ```
> 
> 当变量对象（函数也是对象）遇到一些情况的时候，会偷偷地调用 toString 和 valueOf 方法（隐式调用），那我们就可以改写这两个方法做一些事。

可以展开说说哪些情况会调用 valueOf 吗？

**Comment by kairos1874** [comment]
> ```js
> function add() {
> 	const _args = [...arguments];
> 	function fn() {
> 		_args.push(...arguments);
> 		return fn;
> 	}
> 	fn.valueOf = function() {
> 		return _args.reduce((sum, cur) => sum + cur);
> 	}
> 	return fn;
> }
> add(1)(2)(3)(4).valueOf();
> add(1)(1,2,3)(2).valueOf();
> ```
> 
> 当变量对象（函数也是对象）遇到一些情况的时候，会偷偷地调用 toString 和 valueOf 方法（隐式调用），那我们就可以改写这两个方法做一些事。

不同意这个做法，不应该去改 valueOf
下面是我的做法

```
function add (a) {
  return function (b) {
    if (typeof b === 'number') {
      return add(a+b);
    }
    return a;
  };
};`

const calc = add(1)(2)(3)(4)(5)(6);
const res = calc();
```

**Comment by Ha0ran2001** [comment]
```js
function add(a) {
	function sum(b) {
		a = a + b;
		return sum;
	}

	sum.toString = function () {
		return a;
	};

	return sum;
}
```

**Comment by aztack** [comment]
建议：题目描述需要更严谨些；考点不刻意隐晦
```
实现add函数，使得：
add(1)(2)(3)(4)输出结果为10
add(1)(2)(3)输出结果为6
请给出满足普遍条件的答案，写出你的实现思路和完整代码
```
改为
```
实现add函数使得：
add(1)(2)...(n-1)(n)返回1+2+...n-1+n的结果，其中n>=1
```
这样可以避免得到只针对示例n=4和n=3的答案。
可能原始描述中的“普遍条件”就是想表达这个意思吧。

另外，这道题即便改成第二种描述方式，应该也是无法实现的。因为没有终止条件：
`add`无法确定应该返回`累加和`还是`一个函数`。这就导致大家偏向`toString`、`valueOf`的隐式转换。
然而众所周知JavaScript中的操作符重载很不完善；隐式转换也是应该避免的。
那么题目描述还不如改成：
```
实现add函数使得：
add(1)(2)...(n-1)(n)()返回1+2+...n-1+n的结果，其中n>=1
```
或者
```
实现add函数使得：
add(1)(2)...(n-1)(n).value返回1+2+...n-1+n的结果，其中n>=1
```

另外一个问题：
大家在上学的时候经常遇到。题目为了“隐藏”考察点，刻意隐含甚至缺少条件。
然而，像缺少条件的情况，在高考这类考试中是不可能出现的。这也是为什么，
不少人高考成绩远高于平时考试；高三最后都要刷真题的原因。
因为平时考试出的题目本身就有问题，出题人的水平肯定也没有高考命题组的高。

如果面试中遇到没有给出限制条件的问题。建议问清楚。或者根据不同限制条件讨论。
刷题的时候也要找质量高的题来刷。

作为面试官，也要注意自己出的题的质量。
题目不仅有`难度`一个维度，还有`区分度`、`效度`、`信度`。

**Comment by Ha0ran2001** [comment]
再来个proxy版本的
```js
function add(n) {
	let sum = n;
	const proxy = new Proxy(function a() {}, {
		get(obj, key) {
			return () => sum;
		},
		apply(receiver, ...args) {
			sum += args[1][0];
			return proxy;
		},
	});
	return proxy;
}
```
apply 会拦截函数的调用

**Comment by Ha0ran2001** [comment]
> > ```js
> > function add() {
> > 	const _args = [...arguments];
> > 	function fn() {
> > 		_args.push(...arguments);
> > 		return fn;
> > 	}
> > 	fn.valueOf = function() {
> > 		return _args.reduce((sum, cur) => sum + cur);
> > 	}
> > 	return fn;
> > }
> > add(1)(2)(3)(4).valueOf();
> > add(1)(1,2,3)(2).valueOf();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当变量对象（函数也是对象）遇到一些情况的时候，会偷偷地调用 toString 和 valueOf 方法（隐式调用），那我们就可以改写这两个方法做一些事。
> 
> 可以展开说说哪些情况会调用 valueOf 吗？

对象到原始值的类型转换会有三种变体，称为hint：第一种是对象到字符串的转换，第二种是对象到数字的转换，第三种是运算符不确定期望值的类型时。为了进行转换，内部会调用三个方法，[Symbol.toPrimitive](hint)，如果这个方法存在的话，否则，如果hint是第一种，会尝试toString和valueOf，无论哪个存在；否则，如果hint是 后面两种会尝试调用valueOf和toString。其中第一种方法处理了所有的转换情况。对于字符串的转换，优先toString，对于数学运算，优先valueOf。

**Comment by alileew** [comment]
前来提供思路，给大家开新的思路：

```javascript
const curry = (fn, ...arg) => {
  // 注意：此处是 >= , 传入的参数大于等于原始函数fn的参数个数，则直接执行该函数
  return arg.length >= fn.length ? fn(...arg) : (..._arg) => curry(fn, ...arg, ..._arg);
}

const addThree = (x, y, z) => x + y + z; // 三数相加
const addFour = (x, y, z, p) => x + y + z + p; // 四数相加

const add = curry(addThree);
add(1)(2)(3); // 6

const add = curry(addFour);
add(1)(2)(3)(4); // 10
```

**Comment by supermanklk** [comment]
```
function binAdd() {
    let _arr = Array.prototype.slice.call(arguments);

    function fn() {
        _arr.push(...Array.prototype.slice.call(arguments))
        return fn;
    }
    fn.valueOf = function() {
        return _arr.reduce((pre, cur) => pre + cur )
    }

    return fn;
    
}

binAdd(1)(2)(4).valueOf()
7
binAdd(1)(2)(4, 9).valueOf()
16


```
