### ISSUE TITLE
面对裁员该怎么办？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#27]
### 发生问题的场景

部门最近效益不好，盛传裁员的消息。为了防止HR恶意裁员，投诉无门，小明希望早做准备。

### 需要解决的问题

请你从以下角度给小明支支招：

- 他需要作何准备？

- 需要收集哪些证据以防万一？

- 聊聊HR会有哪些常见招数？

### 最佳答案评选标准

 请从以上角度谈谈，内容详实、有可操作性是加分项

## 最佳答案

[kasoqian的回答](https://github.com/BetaSu/fe-hunter/issues/27#issuecomment-1080201842)

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是当日18：00左右评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by kasoqian** [comment]
**需要作何准备？**
1. 阅读《劳动合同》，看是否有不利因素，如”考勤未达到要求公司有理由辞退“；
2. 阅读《中华人民共和国劳动法》，大概4000字，有助于你全面了解劳动法相关边界；
3. 任何情况(不限于包括领导说”你明天不用来了“)，事情没处理完之前，保持正常上班节奏，勿留小辫子；
4. 时刻保持录音，可以在沟通中引导出真实的裁员原因，录音是你有效的证据；

**需要收集哪些证据以防万一？**
- 证明自己工作正常(考勤记录，加班记录，获奖记录，同事评价，近期工作截图)；
- 证明是由于第三方原因导致的裁员，从群里讨论有关公司业绩相关信息，沟通中的录音中获取；
- 收集社保缴纳(是否足额缴纳)，加班情况(法定加班是1.5~3倍工资)，公积金缴纳情况
- 以魔法对抗魔法，收集公司违法，违规信息，作为”命悬一线“的抗衡手段；

**生命周期：聊聊HR会有哪些常见招数？**
- **第一阶段：主动劝退**
表明你近期的表现不行，举出若干依据，经公司决定，你不适合为公司继续服务，决定对你进行辞退。
- **第二阶段：协商劝退**
看你掰扯不下来，hr会说”我去征求一下领导的意见“，次日说你也不容易，公司愿意给若干money，作为人道主义安抚费。就你给了赔偿，这事儿别让别人知道了。并要求签订保密协议。
- **第三阶段：抗压劝退**
当协商无果，hr会跟你说，这是你的问题，不是公司的问题。如果你想投诉、举报、仲裁，尽可去走流程，公司不怕。说的再难听点，公司有专门的法务团队，打的起，耗得起。

_一般到第三阶段，很多公司也就放手了，对你进行协商赔偿(低于法定赔偿)，能到这一阶段的那公司着实属于不要face了。_
- **高阶1：庭前调解**
公司收到传票立即和你进行协商，告诉你事情不要闹大，我们怎么怎么弄，你的要求我们能够满足
- **高阶2：庭后调解**
庭审结束后，法官会进行双方调解，看彼此是否接受。
- **高阶3：庭审结束或法院**
如果你拒不要求调解，法官会按照法定对公司进行要求。若仍有争议(极少)则上报法院再审。

**细节流：聊聊HR会有哪些常见招数？**
- 套话：引导你说出你工作存在失误，求证观点(通常hr会偷偷全程录音)；
- 设套：告诉你明天不用来上班，你不来的这几天，就是你的把柄；
- 培训：培训是常用伎俩，告诉你培训不合格，没达到公司的工作要求；
- 坑蒙：告诉你就一个人是特殊待遇，别人都没有拿到这么多的赔偿。

**最后**
- 仲裁"通常"一个月内走完；
- 法律援助律师是免费的，网上也有很多免费的法律咨询，由政府承担；

**tips**
- 在劳动合同中看到和《劳动法》有争议的部分，以《劳动法》为准，劳动合同中的违规部分不生效。
- 工作日加班1.5倍，双休加班2倍，节日、年假加班3倍
- 最低的赔偿是N+1，最高的赔偿是2N

---
**哪些是常见的违法行为？**
1. 不签订劳动合同；
2. 末位淘汰；
3. 不缴纳社保或协商放弃缴纳社保；
4. 不足额缴纳社保，公积金；
5. 试用期无故辞退，第三方原因导致辞退；
6. 不给加班费；
7. 恶意调岗；
8. 未提前签订条约，而扣工资，如迟到扣款等；

**暴力裁员通常出现在哪里？**
视公司规模，公司越小暴力裁员的可能性越大。
极小概率出现在`国家机关`，`外企`，`上市公司`。

---

现在谈起加班费，都说有加班费的都是好公司。殊不知，加班费本身就是劳动者自身的权益一部分。我们热爱从工作中获得成就感，但并不妨碍通过付出获得相应报酬。视今日之局面源从何处起？我们和企业是伙伴，了解这些不是为了和谁做斗争，而是为了保护自身权益，建立良好的用工环境，双向促进。如果大家都行动起来，对违法行为说”不“，相信我们的工作环境会越来越好。

### 从来如此，便对吗？

**Comment by zhuidreamweaver** [comment]
12348
