### ISSUE TITLE
React应用卡顿该如何排查？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#3]
## 问题描述

用户反馈你们的应用操作起来卡顿，应用是**React**开发的，你该如何排查是哪些组件造成性能瓶颈？请写出你的排查步骤

⚠️ 本题的重点是排查组件性能瓶颈，请将重点放在**React**上，而不是通用的性能优化策略

## 最佳答案

[jerry-lllman的回答](https://github.com/BetaSu/fe-hunter/issues/3#issuecomment-1074714192)

## 答题同学须知

最佳答案由`围观同学`的`👍`和[卡颂](https://github.com/BetaSu)共同决定。**非答题相关评论**会被删除，问题相关内容讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)里讨论

## 围观同学须知

对于你满意的答案，请不要吝惜你的`👍`，这是评选**最佳答案**的标准

**Comment by adminfyy** [comment]
react-devtools

**Comment by wanlum** [comment]
1. 先检查是否是网络请求太多，导致数据返回较慢，可以适当做一些缓存
2. 再检查是否是某块资源的bundle太大，可以考虑拆分一下(要是有打包报告类似于 vue-cli的report就更好了)
3. 然后排查一下js代码，是不是某处有过多循环导致占用主线程时间过长
4. 接着检查是否是浏览器某帧渲染的东西太多，导致的卡顿
5. 在页面渲染过程中，可能有很多重复的重排重绘
6. 看看有没有内存泄漏啥的
7. 努力优化组件，是否因为数据变动太多导致的延缓

**Comment by yusonghuilife** [comment]
希望看到两个步骤的答案，首先如何排查，定位到问题后如何优化，有示例最佳

**Comment by jerry-lllman** [comment]
1. 使用 Performance 录制应用快照，查看调用情况
2. 查看network中网络请求情况，是否有资源因过大请求阻塞，导致后续资源无法加载，这种情况一般选择分包或固定资源选择cdn分担（多域名。浏览器设置的http2.0以下同域名仅允许同时最多6个tcp的限制）
3. 可以通过 React Developer Tools 的 Profiler 的 Flamegraph（火焰图）或 Ranked（渲染时长排行榜） 查看各组件的渲染时长，根据对应的组件可以进行排查渲染问题，以下作答：
a). 通过检查代码中是否有重复触发的 useEffect
b). 检查是否有多次不同渲染周期中触发的setState导致的渲染（比如在一个事件中导致的state更新，导致依赖于该state的useEffect触发，而该effect中又有其他的setState，导致多个有依赖项的useEffect不同批次连环触发）
c). 检查是否在某个超大组件中需要渲染的元素过多，可使用子组件可考虑使用 pureComponent，或 React.mome ，或使用useMome来根据依赖项更新子组件，或在父组件中将子组件需要的props通过使用useMome或useCallback缓存，  或在子组件中使用 shouldComponentUpdate 中校验是否需要更新来减少更新
d). 检查是否存在拖拽业务，这类业务一般会导致大量的diff存在，可以的话可以考虑不使用React的方式去实现，使用第三方非React的JS库去实现。
e). 同上情况，存在大量增删改查逻辑，会导致大量的的diff可以检查列表元素是否存在唯一的key，通过key可以让React复用Fiber从而避免重复创建 Fiber节点与 Dom 节点
f). 存在未清除掉的定时器或dom监听事件

**Comment by 0753Lar** [comment]
首先是产生在交互上，此时应用明显已加载
所以可以定位到问题发生于： 用户产生交互之后，  用户接收反馈之前。 
问题的性质属于： 部分操作堵塞了页面的渲染，帧率下降，需要检查js代码。
1. 从流程上，查看是否有不必要的hook导致多次的更新，查看effect回调中是否产生多次重复的开销，能否进行合并，
2. 数据流向上，是否影响到了其他组件的不必要的更新，配合memo等做一层优化。
3. 代码习惯上，是否在组件内频繁的声明大量数据，可以配合useMemo,useCallback等 或者将这些数据抽离到外部减少不必要的重复声明
4. 数据体量上，如果交互后需要与大量数据进行计算导致堵塞，那么能否拆分数据减小计算，或者能否优化时间复杂度。

**Comment by EastblueOkay** [comment]
1. 首先通过 **Network** 面板确定是否是因为接口阻塞导致页面渲染慢。
2. 确定渲染问题之后再观察页面是否出现长列表等DOM数量特别大的情况，适当的采用 **虚拟列表** 渲染该元素集合。
3. 然后再通过 react-dev-tools 的  "Highlight updates when components render" 功能查看是否存在 **没有必要的 render** 。
4. 针对没有必要的render可以采用常用的优化手段：shouldComponentUpdate、PureComponent、useCallback、useMemo、避免key重复、children props等。

 通过上述简单的人为手段初步排查后，接下来使用工具来进一步排查。

5. 使用 react-dev-tools 的 **Profile** 功能，可以清晰的了解到每个组件的**渲染时间**，也可以通过渲染时间维度对组件进行**排序**。针对异常组件再进行观察和优化。
6. 使用 chrome performance 进一步查看 js 的执行，通过火焰图来查看 **帧率和调用栈** ，针对异常的部分进行排查优化。
7. chrome 提供的performance 和 Memory 工具同样也支持 **内存泄漏** 的排查，当通过任务管理器发现页面的内存越来越大不存在减少时，也可通过这些工具来排查内存泄漏的问题。

**Comment by leowux** [comment]
### 问题排查
通过 **React Developer Tools** 的 **Profiler** 分析你的 React 应用，然后根据分析结果的 **FlameGraph（火焰图）** 或 **Ranked（渲染排名）** 去定位出现性能问题的组件。我们需要关注 **组件渲染时长** 和 **组件渲染次数** 这两个参数。如果一个组件的渲染次数过多，我们还需要通过 Render 信息窗口中的 **Why did this render?** 查看组件多次渲染的原因，看一看是否是组件需要渲染的状态更新引发的渲染（如果不是的话则组件的渲染为 **非必要重新渲染**）。
### 解决方案
如果问题的原因是**组件单次渲染时间过长**，我们可以用过以下方式优化：
1. 使用 `useMemo` 对组件内部昂贵的计算进行缓存，避免组件更新时重复的计算。
2. 对于经常增删或者交换的元素，为其添加唯一的 `key` 属性，避免其在 Dom Diff 的过程中被重新创建。
3. 对于应用中出现长列表等 DOM 元素过多的情况，我们可以使用**虚拟列表**技术，只渲染部分 DOM 节点。

如果问题的原因是**组件非必要重新渲染**，可以通过以下方式优化：
1. 如果组件的 `props` 没有发生改变，我们可以使用 `React.memo` 包裹组件，避免其父组件更新引发的非必要渲染。
2. 如果组件的 `props` 发生了改变，我们可以追溯其 `props` 的源头，如果是回调函数，我们可以使用 `useCallback` 包裹，避免函数引用改变所引发的重渲染。
