### ISSUE TITLE
为什么Vue没有React那么多性能优化API？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#30]
### 发生问题的场景

`React`中有很多与性能优化相关的API，比如：

- PureComponent

- React.memo

- useMemo、useCallback

- shouldComponentUpdate

### 需要解决的问题

这些API增加了`React`新人的学习成本，反观`Vue`性能优化相关的API却很少，这是为什么呢？

### 最佳答案评选标准

1. 条理清晰，回答有逻辑性

## 最佳答案

[a145789的回答](https://github.com/BetaSu/fe-hunter/issues/30#issuecomment-1081361426)

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是当日18：00左右评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by nonzzz** [comment]
首先jsx过于灵活在js的语义下难以优化,vue的`sfc`模式。在模板层是一种指令式的`DSL`有自己的文法。在编译的时候相较于灵活的jsx他能准确的提升`vnode`，blockerTree配合`patchFlag`精准更新。在性能优化上会更好。
有的人可能会问了。这和API有什么关系。的的确确没啥关系。我们纵观`vue3`也推出了熟悉的`v-memo`这样的指令。但是在之前是没有的。正是得益于`vue`优秀的性能。我们可以举个例子两者都是70分。但是`vue`的上限更高一点.但是对react不熟练的同学很容易导致70分变成60分。`react`更多的是把选择权力交给用户。而`vue`是独自背负了一切。

**Comment by Dante-dan** [comment]
1. `react` 采用了 `jsx` 语法来书写 UI 逻辑，自由灵活的 jsx 语法就很难在转义时做一些静态分析和优化；`vue` 采用 `sfc` 的思路来组织 UI，更方便在转义时做一些优化；
2. `react` 的采用了 `Fiber` 的架构，支持（近似）可打断的渲染过程，将渲染细节尽可能的提供给了开发者。而 `vue` 在编译上的优化使得这些渲染细节没有必要暴露给开发者，同时这些优化可能也就没有那么必要；
3. 由于设计思路上的不同，最终就导致了 API 上的差异。

**Comment by childrentime** [comment]
这个问题，我觉得可以从 react conf 2021黄玄的宣讲谈一谈，react之所以需要那么性能优化，是因为JSX太灵活了。
![image](https://user-images.githubusercontent.com/58261676/160524912-488e63df-a8db-42c7-86bd-c3c4c0b70c80.png)
组件的prop值修改的时候，子组件会不断的re-render,即使有些函数根本不需要进行重复执行，所以我们需要 useMemo() 去缓存我们的组件， useCallBack()去缓存我们的函数。当然 React 官方团队也在努力地去解决这个事情，这个就是 React Forget啦，也就是 react的编译时优化。
那么 vue 有没有这种优化选项呢？ 其实最新版的 vue 也提供了 v-memo这个指令来跳过diff比较。但是由于 vue使用的是依赖追踪机制，而不是 ImmutableJS 这种不可变更新的方式，不存在过渡重渲染的性能问题。

**Comment by a145789** [comment]
> 原生

```html
<div>
   <h1> Hello World </h1>
   <div> Child </div>
</div>

<script>
    document.querySelector('h1').innerHTML = ''
</script>
```
> react

```jsx
const [state, setState] = useState('Hello World')

setState('')

<div>
   <h1> {state} </h1>
   <Child />
</div>
```

> vue

```js
<template>
    <div>
       <h1> {{state}} </h1>
       <Child />
    </div>
</template>

<script>
defineComponent({
  setup() {
    const state = ref('Hello World'')
    state.value = ''
  },
})
</script>
```

`document.querySelector('h1').innerHTML = ''` 基本上就是我们能做到的最细粒度更新，不会影响其他元素，只更新 `h1`

`setState('')` 在 react 机制下本组件、子组件 `Child` 会一起重渲染，因此必须有什么机制去阻止或者减少子组件去做无意义的更新，暴露出了一大堆 `API`

`state.value = ''` 只会更新本组件，不会影响子组件 `Child`，得益于 `vue` 的响应式机制，每个组件只对自己 watcher 负责，父子组件没什么关联，基本可以做到你玩你的我玩我的

> 卡颂补充：`React`机制中每次`setState`，不仅本组件与子组件，实际上整棵组件树都会遍历。同时文中提到的**本组件、子组件 Child会一起重渲染**中的**渲染**，应理解为：组件render，而不是页面渲染

**Comment by lkzwc** [comment]
# 首先我们来说说React中为什么会有这么多的优化API
* 性能、性能
 > 比如我们父子组件嵌套的时候，如果一般没有优化，父组件的刷新会触发组件的刷新，说深入一点，这就是react 的更新机制导致的，调用setState，就会触发组件的重新渲染，还有一点就是父组件更新，子组件也会自动的更新。而且整个diff以及mount过程中都是递归执行的，正是由于这些原因，react中加入了各种优化的钩子useMemo、useCallback等等  去避免各种过度渲染而导致的性能损失
# 为什么VUE中没有这些呢？
> VUE 中组件更新作的足够细致，粒度更小，很容易能够控制组件是否要刷新，当然这些详细展开的话，大致有以下几点需要我们关注
 * Proxy模式
 * 静态标记，标记是否需要更新_createVNode的第四个参数
 * 组件内部Vdom
 * 事件缓存
 * 组件级别watcher
 正是基于以上这些机制，VUE很清楚组件哪里需哟啊更新，哪里不需要更新，即使dom树很复杂

# 总结一下
其实React本身也可以做，将粒度细化，但是为什么没有实现呢，可能是为了更多的自由吧，而VUE直接讲所谓的pure、usememe等优化通过各种手段直接实现了，我们就不需要对其进行操作了，更加对开发这友好，但是失去了灵活性！

**Comment by blackcoffeecat** [comment]
问题中列出的api都有同一个作用：减少组件更新次数；
react的特性：当组件更新时，子组建也会跟随重新渲染；

分析角度1  数据类型不同：
vue其实自带了PureComponent、memo、shouldComponentUpdate的作用，props、state都会转换成reactive对象(vue2是observable)，如果只从组件更新角度看， vue约等于把props和state都shallowEqual比对过了
react的数据传递是flux模式，组件更新前和更新后props不是同一个对象，需要通过shallowEqual或自定义的比对方法来决定组件是否更新，react的一个特性：当组件更新时其所有子组件都会重新渲染
这意味着在react中适当的优化组件更新是有必要的

分析角度2 框架的设计目的：
react本质只是维护虚拟dom，负责数据更新响应到虚拟dom节点更新这个工作(state > vDOM)，将虚拟dom渲染到载体上的工作由react-dom、react-native负责(vDOM > UI)
vue同时也负责渲染的工作，也得益于vue模版编译的内在特性，组件更新的过程可优化到实际渲染级别(state > UI)
从这个角度看，react的props和state只是存粹属于虚拟dom的声明部分，开发者只能通过上述的api来控制虚拟dom的更新，进而优化实际渲染性能

**Comment by 0x-jerry** [comment]
为什么没有这么多 API？大概是因为不需要吧。

先看看两个例子，[React](https://codesandbox.io/s/render-react-32jm12) vs [Vue](https://codesandbox.io/s/render-vue-vg42z0)。

两个里面实现的都是同样的功能：一个 `Counter` 组件里面，包含一个 `SubCounter` 组件。

1. 先看看 React 怎么处理的，[Demo](https://codesandbox.io/s/render-react-32jm12)

`Counter.js`:
```jsx
import { useState } from "react";
import SubCounter from "./SubCounter";

export default function Counter() {
  const [count, setCount] = useState(0);
  console.log("render counter");

  return (
    <div>
      counter:{" "}
      <div>
        <button onClick={() => setCount((n) => n + 1)}>+1</button>
        &nbsp;
        {count}
      </div>
      subcounter:
      <SubCounter />
    </div>
  );
}

```

`SubCounter.js`
```jsx
import { useState } from "react";

export default function Counter() {
  const [count, setCount] = useState(0);
  console.log("render counter1");

  return (
    <div>
      <button onClick={() => setCount((n) => n + 1)}>+1</button>
      &nbsp;
      {count}
    </div>
  );
}

```

从下面的图片可以看出，点击一次 `Counter` 的 +1，会导致 `SubCounter` 的 `render` 函数执行一次。

<img width="554" alt="image" src="https://user-images.githubusercontent.com/14226737/160527849-404de74e-e18e-4cc9-9024-91074228d453.png">

3. 再看看 Vue 怎么处理的，[Demo](https://codesandbox.io/s/render-vue-vg42z0)。

`Counter.js`
```js
import { defineComponent, h } from "vue";
import SubCounter from "./SubCounter";

export default defineComponent({
  data() {
    return {
      count: 0
    };
  },
  render() {
    console.log("render counter");

    return h("div", [
      "counter:",
      h(
        "button",
        {
          onClick: () => {
            this.count++;
          }
        },
        "+1"
      ),
      this.count,
      h("div", ["sub counter:", h(SubCounter)])
    ]);
  }
});
```

`SubCounter.js`
```js
import { defineComponent, h } from "vue";

export default defineComponent({
  data() {
    return {
      count: 0
    };
  },
  render() {
    console.log("render sub counter");

    return h("div", [
      h(
        "button",
        {
          onClick: () => {
            this.count++;
          }
        },
        "+1"
      ),
      this.count
    ]);
  }
});
```

从下面的图片可以看出，点击一次 `Counter` 的 +1，只会执行 `Counter` 的 `render` 函数，`SubCounter` 的 `render` 函数不会执行。

<img width="573" alt="image" src="https://user-images.githubusercontent.com/14226737/160528146-a2455baa-7182-4840-a54d-2bae766a61a6.png">

这大概也就是 Vue 和 React 的区别了，React 把控制权交给的开发者自己，有性能要求的地方，就需要自己去优化。而 Vue 把这部分直接帮开发者做了，如果使用 SFC 的话，将会有更多的优化。具体的优化，可以看看[这个文档](https://staging-cn.vuejs.org/guide/extras/rendering-mechanism.html#compiler-informed-virtual-dom)

**Comment by xuelongm** [comment]
## 1. 框架设计
前端框架，如果运行时类型区分可以分为三类：运行时，编译+运行时，纯编译型，运行时框架主要是react，vue属于编译+运行时框架，纯编译型框架主要包括solid，svelte等。因为react属于运行时框架，在编译阶段可以做的事情比较少（主要原因是react是用jsx实现的，jsx太过灵活很难实现编译阶段优化），也就需要在运行阶段做优化。而vue是编译+运行时的框架，在编译阶段可以做很多优化处理，好比说静态DOM的提升：
![image](https://user-images.githubusercontent.com/18670705/160594522-1aa08364-b73b-483e-a51c-7a3375ef8ef3.png)
这就导致了react学习曲线到陡峭，而vue相对来说比较简单
## 2. 设计思想
vue主要的设计思想是为了满足简单，好用，性能较好，这就导致vue在设计开发阶段必须不能太增加用户的心智负担。react一开始的定位就是提出 UI 开发的新思路。react要做的就是用更好的方式去颠覆前端的开发方式。所以react一开始就引入了jsx，不可变等关机因素。
