### ISSUE TITLE
如何跨团队推进项目落地？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#35]
### 发生问题的场景

小明今年的 OKR 是自研监控埋点系统并跨多个团队推进项目落地，这是他第一次负责需要跨多个团队的项目，你可以从以下几点给他建议么？

### 需要解决的问题

1.跨团队推进项目落地的过程中有哪些坑点需要注意？

2.跨团队推进项目落地有哪些好的方法论或原则？

## 最佳答案

[Gamehu的回答](https://github.com/BetaSu/fe-hunter/issues/35#issuecomment-1082541379)

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是当日18：00左右评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by Gamehu** [comment]
我的做法的大体思路是：**目标为牵引，跟进过程，验证结果。** 

### 目标为牵引：
   > 大家认识拉齐，工作内容清晰。

   1. 建立目标，一定要smart，特别是对交付物和时间节点的说明。【这一步是让大家目标对齐尽可能的避免后期甩锅以及一些其它的幺蛾子】
   2. 确定好每个目标的干系人，拉群，该目标的所有过程讨论等信息在群里直接交流，记得拉上各team的leader或者sm。【这一步主要是为了沟通的实时性，以及及时同步各种信息】

### 跟进过程：

 > 主要是保证整个过程是相对可控可度量的。但是注意任何方式都尽量不打断成员们的工作节奏。

   1. 统一过程产物、交付物等存储路径，比如公司的confluece上单独建个目录，如果公司没有就用个在线的shimo、语雀等。【这一步是归拢所有文件、文字，方便积累以及查阅】
    
   2. 可以适当按照Scrum的方式来运转，比如站会（每天同步进度、问题、识别风险）、backlog（目标或者交互物的拆解）、看板（落实人、时间等）、sprint（对目标、backlog划段，清晰每个阶段的交付物）。【这一步就是落地的关键了，让每个人清楚自己要做的】
    
   3. 邮件也是需要的（通常是需要广播给更高的leader或者整个相关团队的内容，比如风险同步、阶段性目标的达成情况等）。
   4. 周会（两周一次，必要时也可一周一次，时间不宜过长30分钟左右最佳，主要是为了大家坐下来一起聊一聊顺便做个总结）。【这一步尽量轻松，能增进大家的感情那是最好，如果不行也不强求】
   5. 问题复盘会（酌情而定，主要是一起谈谈怎么避免类似的问题，千万注意两点，第一不要针对人，第二不要先下结论）。【这一步主要是为了提醒大家，类似的问题不要犯以及遇到了该怎么解，同时要严肃对待自己的交付成果】
    
### 验证结果：

 > 个人认为结果的质量和完成的快慢，各种教训和经验告诉我前者更重要。可以借助一些工具。

   1.   Code Reviw（酌情制定策略，避免引起抵触情绪）。【这一步做起来比较难但是很有用，多多少少会给大家提个醒，别写屎一样的代码。你想想你接别人代码的时候的那种生不如死】
  
   3.  代码扫描（统一插件）、代码提交规范（git hooks等）、单元测试、自测计划、交叉验证等。【这一步，保证交到测试和PO等手上是不会出现退测以及透支信任的情况】
    
   4.  研发、测试、验收、压测、安装包等环境隔离（这个可能大家觉得很基础，但是相信我效果真的因人而异），研发用研发环境、测试用测试环境、PO/UE/UX用验收环境、压测用专门的环境、集成测试用安装包环境。不允许跨环境验证。【这一步主要是为了避免扯皮以及保障交互物的质量，这种时候“我的环境没问题啊”类似这种话就来不了了，不管谁提的问题，别杠，自己老老实实解决问题】
     
     


_另外多说一句，你的目的是为了能让事情落地能拿到好的结果，不是去伺候谁也不能居高临下，有问题就解决问题，保证各方信息与干系人和领导对齐，实在觉得自己不擅长或者不能解的，及时寻求帮助，比如自己的前辈、技术大佬、领导等，千万别硬扛。_

内容中涉及的某些部分是我们部门层面整体提供的支持或者规范，比如CI/CD、质量门禁等，希望对大家有所帮助，peace。

**Comment by zoro-r** [comment]
**前期准备**

-  和自己的领导通气确定好对应的目标与方向；(和领导通完气，后面的事情才好办)
-  写出当前项目详细的需求文档和估算对应的功能人力安排；
-  找各部门的领导进行沟通与人力调配；
-  确定好某些团队激励方案；聚餐 + 现金奖励不等

**开发实施过程**
这个可以借助一些市面上的敏捷开发团队管理工具进行操作
直接来链接 https://pingcode.com/solutions/scrum?utm_source=baidu1&utm_medium=pc-cpc&utm_campaign=%E6%95%8F%E6%8D%B7&utm_content=scrum-%E5%BC%80%E5%8F%91&utm_term=scrum%E5%BC%80%E5%8F%91&e_matchtype=2&e_creative=57916938545&e_adposition=cl1&e_pagenum=1&e_keywordid=387307160082&bd_vid=11958633445329367504

**项目推广**
先使用边缘项目进行适用,收集使用过程中的反馈意见，进行优化 功能迭代
当项目稳定运行了一段时间且有很好的价值的时候，进行公司内部推广

**Comment by eyea** [comment]
### 一、跨团队推进项目落地的过程中有哪些坑点需要注意？

A. 自研监控埋点系统本身是否够“硬”
1. 是否稳定，线上问题少到可以忽略
2. 是否方便需求方接入和使用 友好型如何
3. 在需求方接入和使用过程中是否有对应的技术提供支持

B. 集团、BU主要领导的重视程度(该系统是否引起领导重视以及支持，这个很重要)
1. 你是否有明确的的落地目标团队，自己要心知肚明；
2. 这些你的目标团队 你能把握有几能成功，有预期；
3. 这些把握不大的团队是否对监控系统有需求，换言之，你的推进有多少理由，有多大的分量；

### 二、跨团队推进项目落地有哪些好的方法论或原则？
1. 推荐自顶向下来进行这类跨部门落地推进业务 (奉旨办事，相当于你手握尚方宝剑去开展工作)；
2. 了解你的系统能给落地团队带来多大的收益，为他人着想，成就他人，也就是成就自己；
3. 进度、关键节点、日常工作相关的沟通要有记录归档，把共识落实在白纸黑字上；
4. 你的态度和行动决定你成就的高度和完成度；
