### ISSUE TITLE
首屏渲染白屏时间如何优化？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#4]
## 问题描述

接用户反馈，你司网站`首次进入`到`内容出现`间会有一段不小的`白屏时间`。该网站是用`前端框架`开发的`CSR`（Client Side Rendering，客户端渲染）应用，请以如下顺序回答：

1. 如何分析首屏加载CSR的性能？
2. 分析后如何找出CSR性能瓶颈？
3. 如何解决CSR性能瓶颈？
4. 有没有其他渲染方案可以解决CSR当前问题，他的原理是什么？

## 最佳答案

[jerry-lllman的回答](https://github.com/BetaSu/fe-hunter/issues/4#issuecomment-1075856575)

### 答题同学须知

最佳答案由`围观同学`的`👍`和[卡颂](https://github.com/BetaSu)共同决定。**非答题相关评论**会被删除，问题相关内容讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)里讨论

### 围观同学须知

对于你满意的答案，请不要吝惜你的`👍`，这是评选**最佳答案**的标准

**Comment by nonzzz** [comment]
先说情况。csr 的首屏加载时间过长一直都是痛点,本体并无 ssr 需求,所以 ssr 相关的解决方案也不会提供。让我们先分析为什么你的网站白屏时间那么久

### 为什么会白屏

这是一个老生常谈的问题无非离不开资源过大,加载方式不合理,以及 csr 本身的瓶颈以及服务器的配置相关。这里我将从这几个维度给出我个人的解决方案。各位可以酌情考虑纳入适用范围。

#### 服务器与 CDN 的解决方式

合理的配置资源缓存方式,以及选用靠谱的 CDN 服务。服务端启用`gzip`等压缩模式压缩这些静态资源加快传输

#### 静态资源优化

关于 gzip 压缩这些是老生常谈的话题这里也不再赘述，就从几个压缩工具谈谈我个人的感受,css 角度上我会倾向于使用`clean-css`他的压缩效率是很高的相较于`css-nao`依附于`postcss`生态而言,再从图片压缩的角度来看`tinypng`也是一样的。

减少静态资源的体积。压缩静态资源其实是一种`footgun`与其思考压缩体积。不如从源头上解决开发这些的方式,比如采用原子化 css 或者`css in js`减少 css 文件的占用比。更小的 css 不仅减少了流量的传输,由于浏览器不需要在解析无用的 css rule 渲染性能的提升也是显而易见的。

明确你的图片宽高也就是`width`和`hegiht`属性,这样可以避免图片响应造成的`layout shift`。

当我们完成了静态资源的压缩,以什么顺序进行发送呈现给用户是极其重要的。本次答题的重点还是得契合`首屏资源加载的体验`,那么我们就得避免`Blocking script`阻塞页面的渲染和加载，所以在我们加载这些`script`的时候我们应该把一些不重要的脚本异步加载,确保首屏资源的最高优先级，对于直接影响渲染的`script`例如(`dark mod`)我们则应该把他们内联到 html 的`<head />`中，这样他就会在`Parser HTML`的阶段执行啦。媒体资源例如图片等我们就需要做`lazy-load`这样我们就能保证在不同浏览器上我们优先加载的资源只有`html`和`css`,不论浏览器如何为其分配带宽和优先级都不会显著的影响白屏时间。

#### 脚本的加载执行

延迟非关键资源的加载，加速`css`传送。我们可以在服务端启用`http2`加速资源的发送这样我们就可以节省一个`RTT`达到更快的解析渲染,确保第三方资源`javascript`的异步加载。比如你在使用`element`,`antd`这些 cdn 资源我们应该在`<script />`上设置`async`。什么你不知道`async`和`defer`？`defer`就是上文说到的`blocking script`，`async`就是当 HTML 解析到开始加载他是无视`DOM`和渲染以及`onload`的。而现代浏览器的正确做法应该是使用`DOM`动态创建`script async`标签去加载资源。
现有大部分的框架以及`bundle`工具都支持切割代码我们可以把这些资源都切割保证首屏的`js`足够轻量级。

#### 优化你的 css

优化你的 css 选择器。css 的渲染取决于一组匹配选择器 不合理的选择器会导致解析过慢,css 选择器的解析顺序是从右到左，所以在面对复杂的 css 场景我们应该根据`Steve Souders`大师总结的`css`选择器性能排行合理的选择方案达到更快的解析以及渲染。

#### 采用 SSR(同构渲染)

上述是通用的资源响应解决手段。但是`csr`总归是有作为`csr`的局限性。这时候我们就得回归本质`ssr`在服务端解析出了所有的`dom`生成了`string`这样在访问的时候和`csr`需要解析在合成渲染是截然不同的,现代的`ssr`框架允许模块采用`csr`加载我们可以在首屏重要的部分进行`ssr`其他采用`csr`。合理的搭配我们的渲染结构。

**Comment by shenzhim** [comment]
> 先说情况。csr 的首屏加载时间过长一直都是痛点,本体并无 ssr 需求,所以 ssr 相关的解决方案也不会提供。让我们先分析为什么你的网站白屏时间那么久
> 
> ### 为什么会白屏
> 这是一个老生常谈的问题无非离不开资源过大,加载方式不合理,以及 csr 本身的瓶颈以及服务器的配置相关。这里我将从这几个维度给出我个人的解决方案。各位可以酌情考虑纳入适用范围。
> 
> #### 服务器与 CDN 的解决方式
> 合理的配置资源缓存方式,以及选用靠谱的 CDN 服务。服务端启用`gzip`等压缩模式压缩这些静态资源加快传输
> 
> #### 静态资源优化
> 关于 gzip 压缩这些是老生常谈的话题这里也不再赘述，就从几个压缩工具谈谈我个人的感受,css 角度上我会倾向于使用`clean-css`他的压缩效率是很高的相较于`css-nao`依附于`postcss`生态而言,再从图片压缩的角度来看`tinypng`也是一样的。
> 
> 减少静态资源的体积。压缩静态资源其实是一种`footgun`与其思考压缩体积。不如从源头上解决开发这些的方式,比如采用原子化 css 或者`css in js`减少 css 文件的占用比。更小的 css 不仅减少了流量的传输,由于浏览器不需要在解析无用的 css rule 渲染性能的提升也是显而易见的。
> 
> 明确你的图片宽高也就是`width`和`hegiht`属性,这样可以避免图片响应造成的`layout shift`。
> 
> 当我们完成了静态资源的压缩,以什么顺序进行发送呈现给用户是极其重要的。本次答题的重点还是得契合`首屏资源加载的体验`,那么我们就得避免`Blocking script`阻塞页面的渲染和加载，所以在我们加载这些`script`的时候我们应该把一些不重要的脚本异步加载,确保首屏资源的最高优先级，对于直接影响渲染的`script`例如(`dark mod`)我们则应该把他们内联到 html 的`<head />`中，这样他就会在`Parser HTML`的阶段执行啦。媒体资源例如图片等我们就需要做`lazy-load`这样我们就能保证在不同浏览器上我们优先加载的资源只有`html`和`css`,不论浏览器如何为其分配带宽和优先级都不会显著的影响白屏时间。
> 
> #### 脚本的加载执行
> 延迟非关键资源的加载，加速`css`传送。我们可以在服务端启用`http2`加速资源的发送这样我们就可以节省一个`RTT`达到更快的解析渲染,确保第三方资源`javascript`的异步加载。比如你在使用`element`,`antd`这些 cdn 资源我们应该在`<script />`上设置`async`。什么你不知道`async`和`defer`？`defer`就是上文说到的`blocking script`，`async`就是当 HTML 解析到开始加载他是无视`DOM`和渲染以及`onload`的。而现代浏览器的正确做法应该是使用`DOM`动态创建`script async`标签去加载资源。 现有大部分的框架以及`bundle`工具都支持切割代码我们可以把这些资源都切割保证首屏的`js`足够轻量级。
> 
> #### 优化你的 css
> 优化你的 css 选择器。css 的渲染取决于一组匹配选择器 不合理的选择器会导致解析过慢,css 选择器的解析顺序是从右到左，所以在面对复杂的 css 场景我们应该根据`Steve Souders`大师总结的`css`选择器性能排行合理的选择方案达到更快的解析以及渲染。
> 
> #### 采用 SSR(同构渲染)
> 上述是通用的资源响应解决手段。但是`csr`总归是有作为`csr`的局限性。这时候我们就得回归本质`ssr`在服务端解析出了所有的`dom`生成了`string`这样在访问的时候和`csr`需要解析在合成渲染是截然不同的,现代的`ssr`框架允许模块采用`csr`加载我们可以在首屏重要的部分进行`ssr`其他采用`csr`。合理的搭配我们的渲染结构。

“defer就是上文说到的blocking script” defer怎么会是blocking script？

**Comment by nonzzz** [comment]
> > 先说情况。csr 的首屏加载时间过长一直都是痛点,本体并无 ssr 需求,所以 ssr 相关的解决方案也不会提供。让我们先分析为什么你的网站白屏时间那么久
> > ### 为什么会白屏
> > 这是一个老生常谈的问题无非离不开资源过大,加载方式不合理,以及 csr 本身的瓶颈以及服务器的配置相关。这里我将从这几个维度给出我个人的解决方案。各位可以酌情考虑纳入适用范围。
> > #### 服务器与 CDN 的解决方式
> > 合理的配置资源缓存方式,以及选用靠谱的 CDN 服务。服务端启用`gzip`等压缩模式压缩这些静态资源加快传输
> > #### 静态资源优化
> > 关于 gzip 压缩这些是老生常谈的话题这里也不再赘述，就从几个压缩工具谈谈我个人的感受,css 角度上我会倾向于使用`clean-css`他的压缩效率是很高的相较于`css-nao`依附于`postcss`生态而言,再从图片压缩的角度来看`tinypng`也是一样的。
> > 减少静态资源的体积。压缩静态资源其实是一种`footgun`与其思考压缩体积。不如从源头上解决开发这些的方式,比如采用原子化 css 或者`css in js`减少 css 文件的占用比。更小的 css 不仅减少了流量的传输,由于浏览器不需要在解析无用的 css rule 渲染性能的提升也是显而易见的。
> > 明确你的图片宽高也就是`width`和`hegiht`属性,这样可以避免图片响应造成的`layout shift`。
> > 当我们完成了静态资源的压缩,以什么顺序进行发送呈现给用户是极其重要的。本次答题的重点还是得契合`首屏资源加载的体验`,那么我们就得避免`Blocking script`阻塞页面的渲染和加载，所以在我们加载这些`script`的时候我们应该把一些不重要的脚本异步加载,确保首屏资源的最高优先级，对于直接影响渲染的`script`例如(`dark mod`)我们则应该把他们内联到 html 的`<head />`中，这样他就会在`Parser HTML`的阶段执行啦。媒体资源例如图片等我们就需要做`lazy-load`这样我们就能保证在不同浏览器上我们优先加载的资源只有`html`和`css`,不论浏览器如何为其分配带宽和优先级都不会显著的影响白屏时间。
> > #### 脚本的加载执行
> > 延迟非关键资源的加载，加速`css`传送。我们可以在服务端启用`http2`加速资源的发送这样我们就可以节省一个`RTT`达到更快的解析渲染,确保第三方资源`javascript`的异步加载。比如你在使用`element`,`antd`这些 cdn 资源我们应该在`<script />`上设置`async`。什么你不知道`async`和`defer`？`defer`就是上文说到的`blocking script`，`async`就是当 HTML 解析到开始加载他是无视`DOM`和渲染以及`onload`的。而现代浏览器的正确做法应该是使用`DOM`动态创建`script async`标签去加载资源。 现有大部分的框架以及`bundle`工具都支持切割代码我们可以把这些资源都切割保证首屏的`js`足够轻量级。
> > #### 优化你的 css
> > 优化你的 css 选择器。css 的渲染取决于一组匹配选择器 不合理的选择器会导致解析过慢,css 选择器的解析顺序是从右到左，所以在面对复杂的 css 场景我们应该根据`Steve Souders`大师总结的`css`选择器性能排行合理的选择方案达到更快的解析以及渲染。
> > #### 采用 SSR(同构渲染)
> > 上述是通用的资源响应解决手段。但是`csr`总归是有作为`csr`的局限性。这时候我们就得回归本质`ssr`在服务端解析出了所有的`dom`生成了`string`这样在访问的时候和`csr`需要解析在合成渲染是截然不同的,现代的`ssr`框架允许模块采用`csr`加载我们可以在首屏重要的部分进行`ssr`其他采用`csr`。合理的搭配我们的渲染结构。
> 
> “defer就是上文说到的blocking script” defer怎么会是blocking script？

![image](https://user-images.githubusercontent.com/52351095/159611909-95c162c6-0c23-4487-a1f9-f44139586f68.png)
MDN请
这里解释下为什么他还是`blocking script`因为`domXXX`事件被阻塞了。

**Comment by shenzhim** [comment]
> > > 先说情况。csr 的首屏加载时间过长一直都是痛点,本体并无 ssr 需求,所以 ssr 相关的解决方案也不会提供。让我们先分析为什么你的网站白屏时间那么久
> > > ### 为什么会白屏
> > > 这是一个老生常谈的问题无非离不开资源过大,加载方式不合理,以及 csr 本身的瓶颈以及服务器的配置相关。这里我将从这几个维度给出我个人的解决方案。各位可以酌情考虑纳入适用范围。
> > > #### 服务器与 CDN 的解决方式
> > > 合理的配置资源缓存方式,以及选用靠谱的 CDN 服务。服务端启用`gzip`等压缩模式压缩这些静态资源加快传输
> > > #### 静态资源优化
> > > 关于 gzip 压缩这些是老生常谈的话题这里也不再赘述，就从几个压缩工具谈谈我个人的感受,css 角度上我会倾向于使用`clean-css`他的压缩效率是很高的相较于`css-nao`依附于`postcss`生态而言,再从图片压缩的角度来看`tinypng`也是一样的。
> > > 减少静态资源的体积。压缩静态资源其实是一种`footgun`与其思考压缩体积。不如从源头上解决开发这些的方式,比如采用原子化 css 或者`css in js`减少 css 文件的占用比。更小的 css 不仅减少了流量的传输,由于浏览器不需要在解析无用的 css rule 渲染性能的提升也是显而易见的。
> > > 明确你的图片宽高也就是`width`和`hegiht`属性,这样可以避免图片响应造成的`layout shift`。
> > > 当我们完成了静态资源的压缩,以什么顺序进行发送呈现给用户是极其重要的。本次答题的重点还是得契合`首屏资源加载的体验`,那么我们就得避免`Blocking script`阻塞页面的渲染和加载，所以在我们加载这些`script`的时候我们应该把一些不重要的脚本异步加载,确保首屏资源的最高优先级，对于直接影响渲染的`script`例如(`dark mod`)我们则应该把他们内联到 html 的`<head />`中，这样他就会在`Parser HTML`的阶段执行啦。媒体资源例如图片等我们就需要做`lazy-load`这样我们就能保证在不同浏览器上我们优先加载的资源只有`html`和`css`,不论浏览器如何为其分配带宽和优先级都不会显著的影响白屏时间。
> > > #### 脚本的加载执行
> > > 延迟非关键资源的加载，加速`css`传送。我们可以在服务端启用`http2`加速资源的发送这样我们就可以节省一个`RTT`达到更快的解析渲染,确保第三方资源`javascript`的异步加载。比如你在使用`element`,`antd`这些 cdn 资源我们应该在`<script />`上设置`async`。什么你不知道`async`和`defer`？`defer`就是上文说到的`blocking script`，`async`就是当 HTML 解析到开始加载他是无视`DOM`和渲染以及`onload`的。而现代浏览器的正确做法应该是使用`DOM`动态创建`script async`标签去加载资源。 现有大部分的框架以及`bundle`工具都支持切割代码我们可以把这些资源都切割保证首屏的`js`足够轻量级。
> > > #### 优化你的 css
> > > 优化你的 css 选择器。css 的渲染取决于一组匹配选择器 不合理的选择器会导致解析过慢,css 选择器的解析顺序是从右到左，所以在面对复杂的 css 场景我们应该根据`Steve Souders`大师总结的`css`选择器性能排行合理的选择方案达到更快的解析以及渲染。
> > > #### 采用 SSR(同构渲染)
> > > 上述是通用的资源响应解决手段。但是`csr`总归是有作为`csr`的局限性。这时候我们就得回归本质`ssr`在服务端解析出了所有的`dom`生成了`string`这样在访问的时候和`csr`需要解析在合成渲染是截然不同的,现代的`ssr`框架允许模块采用`csr`加载我们可以在首屏重要的部分进行`ssr`其他采用`csr`。合理的搭配我们的渲染结构。
> > 
> > 
> > “defer就是上文说到的blocking script” defer怎么会是blocking script？
> 
> ![image](https://user-images.githubusercontent.com/52351095/159611909-95c162c6-0c23-4487-a1f9-f44139586f68.png) MDN请 这里解释下为什么他还是`blocking script`因为`domXXX`事件被阻塞了。

blocking script 的概念应该是阻塞dom的渲染吧

**Comment by jerry-lllman** [comment]
对于其他同学回答过的部分我就不展开讲了，我主要讲大体的思路。

一、如何分析首屏加载CSR的性能？
有三种方式进行分析：
1. network（浏览器->DevTools）
2. performance （浏览器->DevTools）
3. lighthouse（浏览器->DevTools）
4. sentry（第三方平台）
5. [**webPageTest**](https://webpagetest.org/) 更全面，更详细，更强大的页面分析
具体怎么操作我就不赘述了，各位自行去看。

二、分析后如何找出CSR性能瓶颈？
按照上面的5种方式来看吧

三、如何解决CSR性能瓶颈？
从CSR方向来讲的话，基本就两个方向了
1. **网络层面**：
从网络方面来讲，就是减少HTTP请求的次数，以及减小请求体积，这里就简单聊几点
a). 将多次请求合并到一次请求（ajax、精灵图，文件合并等）
b). 页面懒加载应该也可以算在这个方面。
c). 缓存住一些不经常改动的文件或内容将请求拦截（service worker）
b). 文件内容压缩
e). 静态资源CDN也是方式之一
f). 升级到 http2


2. **渲染层面**
a). 骨架屏，起码能让用户有打开了网页的感觉
b). 图片懒加载
c). 防抖节流
d). 代码层面的改善吧，很有可能是某些坏代码产生的

四、有没有其他渲染方案可以解决CSR当前问题，他的原理是什么？
SSR。就是将框架代码提前在服务端跑一遍，不过一般除非对SEO要求比较高或者你们公司比较有钱，否则不太会去使用，因为比较占用服务器的资源。

**Comment by WarrenJones** [comment]
https://developers.google.com/web/fundamentals/performance/get-started

**Comment by nonzzz** [comment]
> blocking script 的概念应该是阻塞dom的渲染吧
参见https://bugs.chromium.org/p/chromium/issues/detail?id=611136 。首先我们要明确`DOMContentLoaded`

**Comment by shenzhim** [comment]
> > blocking script 的概念应该是阻塞dom的渲染吧
> > 参见https://bugs.chromium.org/p/chromium/issues/detail?id=611136 。首先我们要明确`DOMContentLoaded`

贴的这个链接，看上去是content type 改为了 application/xhtml+xml导致的问题，看下面的评论说是XMLDocumentLoader不支持defer。
这个跟 defer是不是 blocking script 没什么关系吧

**Comment by nonzzz** [comment]
> 贴的这个链接，看上去是content type 改为了 application/xhtml+xml导致的问题，看下面的评论说是XMLDocumentLoader不支持defer。 这个跟 defer是不是 blocking script 没什么关系吧

因为你DOM完成绘制是要在`DOMContentLoaded`执行完毕的。而`defer`会阻塞这一个过程。

**Comment by shenzhim** [comment]
> > 贴的这个链接，看上去是content type 改为了 application/xhtml+xml导致的问题，看下面的评论说是XMLDocumentLoader不支持defer。 这个跟 defer是不是 blocking script 没什么关系吧
> 
> 因为你DOM完成绘制是要在`DOMContentLoaded`执行完毕的。而`defer`会阻塞这一个过程。

确实，defer会阻塞domcontentloaded事件，但是不能说 defer就是一个blocking script。
阻塞脚本，应该理解成阻塞dom解析，而defer的脚本是不会的

**Comment by nonzzz** [comment]
> 确实，defer会阻塞domcontentloaded事件，但是不能说 defer就是一个blocking script。 阻塞脚本，应该理解成阻塞dom解析，而defer的脚本是不会的

但是 他和`blocking script`造成的效果不是一致的吗hh。按照这样理解的话其实`defer`就不是最佳实践。反倒是动态的create`script async`才是。我理解为`blocking`是因为他和`blocking`是一致性的。

**Comment by shenzhim** [comment]
> > 确实，defer会阻塞domcontentloaded事件，但是不能说 defer就是一个blocking script。 阻塞脚本，应该理解成阻塞dom解析，而defer的脚本是不会的
> 
> 但是 他和`blocking script`造成的效果不是一致的吗hh。按照这样理解的话其实`defer`就不是最佳实践。反倒是动态的create`script async`才是。我理解为`blocking`是因为他和`blocking`是一致性的。

blocking script 会导致dom解析暂停，而 defer script 的下载是不会影响dom解析的。我理解defer的使用场景可以跟preload使用场景一致，defer和async的都不会阻塞dom解析，区别在于js文件加载后的执行顺序不同以及有无对DomContentLoaded的事件影响

**Comment by nonzzz** [comment]
> blocking script 会导致dom解析暂停，而 defer script 的下载是不会影响dom解析的。我理解defer的使用场景可以跟preload使用场景一致，defer和async的都不会阻塞dom解析，区别在于js文件加载后的执行顺序不同以及有无对DomContentLoaded的事件影响

是这样。但往往`async`才是最佳实践，虽然`defer`和`async`近似一样 但是对于解析dom的差异很大。`preload`确实是有这么个场景。

**Comment by shenzhim** [comment]
> > blocking script 会导致dom解析暂停，而 defer script 的下载是不会影响dom解析的。我理解defer的使用场景可以跟preload使用场景一致，defer和async的都不会阻塞dom解析，区别在于js文件加载后的执行顺序不同以及有无对DomContentLoaded的事件影响
> 
> 是这样。但往往`async`才是最佳实践，虽然`defer`和`async`近似一样 但是对于解析dom的差异很大。`preload`确实是有这么个场景。

不能说async就是一定的最佳实践吧
还是根据具体情况来的，如果是一些第三方库并且对执行顺序没有要求时（比如说谷歌的analytics脚本）
如果碰到的场景需要js的执行是需要按照一定的顺序时，使用defer才更合理一点

**Comment by nonzzz** [comment]
> 不能说async就是一定的最佳实践吧 还是根据具体情况来的，如果是一些第三方库并且对执行顺序没有要求时（比如说谷歌的analytics脚本） 如果碰到的场景需要js的执行是需要按照一定的顺序时，使用defer才更合理一点

具体情况具体分析了。这里说下分析工具吧`web-vitals`这个库很棒。可以配合`performance`使用
