### ISSUE TITLE
虚拟DOM的意义是什么？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#46]
### 发生问题的场景

 一些流行的前端框架会使用虚拟DOM技术，比如Vue、React。

### 需要解决的问题

请从以下角度回答：

1. 为什么需要虚拟DOM？
2. 虚拟DOM有哪些优势？
3. 虚拟DOM有哪些劣势？
4. 如果不使用虚拟DOM，还有哪些替代方案？

### 最佳答案评选标准

 按以上角度尽可能详细回答

## 最佳答案

[xwxgjs的回答](https://github.com/BetaSu/fe-hunter/issues/46#issuecomment-1094266938)

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是问题发布24小时后评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by Travelguest** [comment]
### **提高开发效率**

使用`JavaScript 或` `jQuery` ，我们在编写应用程序时，还需关注如何去更新`DOM`。

使用`React`，因为有数据驱动视图，你只需要告诉`React`你想让视图处于什么状态，`React`则通过`VitrualDom`确保`DOM`与该状态相匹配。你不必自己去完成属性操作、事件处理、`DOM`更新，`React`会替你完成这一切。

这让我们**更关注我们的业务逻辑而非`DOM`操作**，这一点即可大大提升我们的开发效率。

### **关于提升性能**

**直接操作`DOM`是非常耗费性能的**，**而JS计算要快的多**，这一点毋庸置疑。但是`React`使用`VitrualDom`也是无法避免操作`DOM`的。

如果是首次渲染，`VitrualDom`不具有任何优势，甚至它要进行更多的计算，消耗更多的内存。

`VitrualDom`的**优势在于**`React`**的**`Diff`**算法复用**`old结点`**找出差异和批处理策略**，在这个过程中`React`帮助我们"提升了性能"。

所以，我更倾向于说，`VitrualDom`帮助我们提高了开发效率，在重复渲染时它帮助我们计算如何更高效的更新，而不是它比`DOM`操作更快。

### **跨浏览器兼容**


`React`基于`VitrualDom`自己实现了一套自己的事件机制（合成事件），自己模拟了事件冒泡和捕获的过程，采用了事件代理，批量更新等方法，**抹平了各个浏览器的事件兼容性问题**。

### **跨平台兼容**


`VitrualDom`为`React`带来了跨平台渲染的能力，**虚拟DOM其实就是一层抽象层，可以让我们写的代码在多端表现一致**。

以`React Native`为例子。`React`根据`VitrualDom`画出相应平台的`ui`层，只不过不同平台画的姿势不同而已。

**Comment by kasoqian** [comment]
要了解虚拟dom的意义，得先了解虚拟dom是什么？。

**虚拟dom是什么？**


简单理解，虚拟dom是真实dom的对象形式。

**dom操作的发展史？**
- 第一阶段：动效为主
这个阶段主要以呈现层为主，展示信息，让用户进行消费。此时对dom的操作主要是一些动效，布局的实现。对dom操作量较少。

- 第二阶段：JQuery阶段
JQuery提供了良好的dom操作方法，如 `$("#root")` 可以链式的对dom进行一系列的操作。从而优化了dom操作。试想一下用JQuery渲染一个数组，并展示在root节点中应该怎么做呢？是不是有点麻烦？

- 第三阶段：模板引擎阶段
这个时候诞生了如pug等模板引擎，可以为dom赋能，直接在模板中修改dom。如下是一个数组循环成pug模板化语法的形式：
````pug
h1 SitePoint JavaScript

ul.team
  each employee in sitePointEmployees
    li
      figure
        img(src=employee.imgSrc alt=`${employee.firstName} ${employee.lastName}`)
        figcaption
          h3 #{employee.firstName} #{employee.lastName}
          p= employee.position
          a(href=employee.twitter target='_blank')
            i.fa.fa-twitter
````

- 第四阶段：虚拟dom阶段

**Comment by blackcoffeecat** [comment]
为什么需要虚拟DOM
虚拟DOM是一种声明式编程语言的设计模式，相反的jQuery应用是一种命令式编程语言。
现代应用中数据和UI的复杂交互需求越来越高，复杂的jQuery应用中我们常常难以从代码中看出数据和UI的关系，UI会因为前后的操作操作而产生变化，在维护代码时需要很抽象的思考UI的变化过程来推断代码是怎么执行和渲染的。
我觉得虚拟DOM就是解决这种痛点而被现代前端开发需要的，可以形成很好的数据和UI关系。

虚拟DOM有哪些劣势
需要额外的性能消耗（大列表是个典型例子

如果不使用虚拟DOM，还有哪些替代方案？
svelte 静态编译框架？

**Comment by Btrya** [comment]
### 为什么需要虚拟DOM，有哪些优势？

我们使用jq、js的去获取dom节点、设置文本内容、绑定事件这种**关注过程**的，我们可以称之为**命令式编程**
而像vue这种直接就是一个 div 里边有自己的属性，语法糖，文本内容等，只**关注结果**的，我们称之为**声明式编程**

使用虚拟DOM的原因很简单，减少疯狂的去获取dom元素，操作dom带来的心智负担，即使他的速度没有js直接操作dom来的更快，但是它**方便**啊，而且也能保证一个**性能下限**，就是你再差再差的情况我也能保证你最差也就到这个性能了

另外虚拟DOM也**方便跨平台操作**，说白了他就是一个js对象，是js能够读得懂的

@Travelguest 大佬也是写的比较清楚了

一句话总结：虚拟DOM降低开发的心智负担，保证性能下限，方便跨平台

### 虚拟DOM有哪些劣势？

首次渲染大量DOM时，由于多了一层虚拟DOM的计算，会比innerHTML插入慢

### 如果不使用虚拟DOM，还有哪些替代方案？

上边提到了降低开发的心智负担，根本原因就是使用的是声明式编程，那么围绕这一点来说，只要是以这个思想出发的应该都算是一种解决方案。

如果从性能上来说，其实虚拟DOM无非是尽可能的减少重绘、回流，那么使用**createDocumentFragment**来解决我认为也是一个比较好的思路出发点？

**Comment by Maidang1** [comment]
# 虚拟DOM目的就是抽象出真实DOM,方便框架在运行时找出更新的差异 然后更新视图

# 对于性能的提升：
框架底层也是要操作DOM的 然后去更新视图。相较于我们手动的操作DOM，有了虚拟DOM之后，框架本身会帮助我们找到最小的更新差异 少量的操作DOM。并不是虚拟DOM本身性能高。

# 多平台
可以实现不同的渲染层，根据不同的平台特性实现响应的代码

**Comment by fxwing** [comment]
抽离真实DOM,对比更新渲染，减少回流

**Comment by NoBey** [comment]
我来换个角度
先说结论, 虚拟dom是发展必然的结果

先说前身 mvc 下的 dom 开发 先定义 model, 然后写一个 模版 view 或者 字符串拼接方法, 然后再 controller 里去跟进业务逻辑去 调用 createView(model) => dom , 再塞回 body, 这个逻辑下, 要往下优化就是 createView 里面 在做一堆 htmlcache 去缓存原本生成的逻辑. 

然后 mvc 自己做了一套 dom 缓存策略

再来看 虚拟dom 这就是再最开始就把这个问题解决啦

**Comment by liu-zhi-fei** [comment]
# 1. 为什么需要虚拟DOM？

一个词：**管理**。

从具体的角度： `React` 借助 `虚拟DOM` **管理**  `浏览器渲染`。

从开发的角度： `开发者` 借助 `抽象化数据` **管理**  `UI`。

举个例子：

假如我们要实现打包工具：将前端项目打包成一个js文件。

我们会想通过字符串，去试下你，但是这其实很难实现，因为字符串的抽象信息太少了。

所以要借助 **抽象语法树**（`AST`）。`AST` 是对代码的抽象表达。

 `webpack` 和 `babel`借助`AST`，**管理**代码。其中查找依赖、Tree Shaking、支持高版本JS特性等多个功能都依赖于`AST`。

**当A要管理B的时候，将B的信息抽象化，才方便A去管理。**

# 2. 虚拟DOM有哪些优势？

- 抽象化数据，方便了`React` 实现多种需求。
- 支持多平台
  - 浏览器、移动端、服务器、自定义的，例如Trao(小程序)，桌面端等。
- 提高开发效率
  - 通过`VDOM`可以将DOM操作，抽象到专门的模块去处理，减少开发者对DOM的操作。
- 性能优化
  - 通过`VDOM` ，来实现组件树的对比，复用DOM节点。
    - 在DIFF上我个人认为，DIFF更多是React帮助自己提升性能。因为React是脏检查，全量树对比。
- 提高可维护性
- 提高可测试
  - `VDOM` 使得前端组件方便进行测试。

# 3. 虚拟DOM有哪些劣势？

- 高运行时
  - 在运行时也要生成和处理`VDOM` ，这部分的运行时开销不小。
- 高内存开销
  - 一棵组件树 `VDOM` 要生成很多对象数据，这会占用很高的内存开销。

# 4. 如果不使用虚拟DOM，还有哪些替代方案？

在运行时没有虚拟DOM的方案：

- 响应式
  - 通过 `date`直接和`view`挂钩，需要借助`Proxy`等。
- 强编译
  - 直接编译出`dom` + `dom操作` + `data`
  - 相当于从前写JS、JQ，但是在编译时进行分析，直接编译出对应DOM和操作和数据的源码。

# 我对问题的疑问

- 问题的虚拟DOM是什么？
  - 我认为React中JSX（ReactElement）、Fiber都算是虚拟DOM。
    - 例如DIFF时，我们说是虚拟DOM在DIFF，React源码就是JSX（ReactElement）和Fiber在进行DIFF。
- 第4问不用虚拟DOM的说法很奇怪，是指在运行时没有虚拟DOM吗？
  - 现在所有的框架都会写`JSX`语法，`JSX` 实际在多数框架中都会被处理为 `VDOM` 。
  - 只是最终结果不同，有多种情况。
    - VDOM只在编译时有。
    - VDOM只在运行时有。
    - VDOM在运行时，编译时都有。
  - 是指抽象化数据，完全没有。处理字符串一样进行处理吗？

提个思考题：HTML文件算不算“虚拟DOM”？

**Comment by ghost** [comment]
> 提个思考题：HTML文件算不算“虚拟DOM”？

DOM = 文档对象模型，HTML = 超文本标记语言。
标记语言描述了文档对象，可以理解为文档对象模型在某种环境下的 DSL。

![图片](https://user-images.githubusercontent.com/77133362/162602574-97ba9aa7-a78f-4e3c-8901-e9ecf9772d40.png)

AST 是对 JavaScript 代码的抽象，那么 DOM 是对 HTML 的抽象？有点奇怪。

不过根据上面的类比，HTML 肯定是不算虚拟 DOM 的。 @liu-zhi-fei

**Comment by xwxgjs** [comment]
## 为什么需要虚拟DOM？


## 虚拟DOM有哪些优势？
## 虚拟DOM有哪些劣势？
## 如果不使用虚拟DOM，还有哪些替代方案？

**Comment by ghost** [comment]
谈论虚拟 DOM 之前，我们先明确一个概念：DOM

根据 MDN 的说法：

> 文档对象模型 (DOM) 是 HTML 和 XML 文档的编程接口。
> 
> 它提供了对文档的结构化的表述，并定义了一种方式可以使从程序中对该结构进行访问，从而改变文档的结构，样式和内容。DOM 将文档解析为一个由节点和对象（包含属性和方法的对象）组成的结构集合。
> 
> 简言之，它会将 web 页面和脚本或程序语言连接起来。

这里有两个重点：

- HTML 和 DOM 之间是有映射关系的，DOM 是对 HTML 的结构化描述
- 通过 DOM 可以对文档进行访问和操作

我们可以建立这样一个对应关系：

`HTML -> DOM -> JS`

换句话说，只要有了 DOM，实际上就可以支撑 Vue、React 等框架对文档的操作了。毕竟现在提到的虚拟 DOM 和 DOM 都是结构化的信息，同样可以进行 diff、patch 操作。

那为什么还需要虚拟 DOM 呢？虚拟 DOM 为我们带来了什么？

首先，添加虚拟 DOM 之后，对应关系变成了这样：

`HTML -> DOM -> 虚拟 DOM -> JS`

从性能上考虑，通过 DOM 提供的接口获取文档的位置、样式，并对其进行更改。如果文档已经被渲染在浏览器中，可能会触发浏览器的重绘和回流机制，如果多次触发，对性能的影响极大。如果说直接操作 DOM，很容易出现这种问题。

那有人会提出：如果没有在屏幕中渲染出来，那么就可以绕过这部分性能开销。我们可以创建一个 DOM 片段出来，这个 DOM 片段不插入到文档中，对这个 DOM 片段进行操作，当一次操作完成后插入到文档中。

> 其实这个方案就是 Canvas 开发时的“离屏层”概念。

这其实有了虚拟 DOM 的影子。

但是这个方案也有问题：框架进行操作时，其实并不需要 DOM 上的那么多方法，这些方法会占用更多的内存空间。

转念一想，既然我已经将 DOM 隔离一层出来，还不如创建一套自己需要的模型，仅保留需要的操作方法。这就是现在用到的虚拟 DOM 了。

这样增加的虚拟 DOM 层，仅保留自己需要的内容，降低了开发者的理解成本。
同时也抹平了不同浏览器引擎对 DOM 操作实现的差异，开发者不需要再关注各个引擎的具体实现了。
后来发现，如果对虚拟 DOM 进行操作，HTML 部分完全可以替换成其他的文档环境，通用性会更强。

所以我们可以回答下面的问题了：
## 为什么需要虚拟 DOM？
1. 为了降低对 DOM 操作引发的渲染开销
2. 为了降低开发者的理解成本
## 虚拟 DOM 有哪些优势？
1. 性能：隔离了对文档的操作，降低渲染成本
2. 跨平台：可以通过一套模型适配多种渲染平台
3. 可维护性：虚拟 DOM 抹平了不同平台 API 的区别，仅保留所需的操作方法，降低理解成本，提升可维护性
## 虚拟 DOM 有哪些劣势？
1. 不适用对真实 DOM 需要操作的场景。使用虚拟 DOM 的框架不建议用户操作 DOM，所有的 DOM 操作都由框架进行。如果你真的需要获取真实 DOM 操作，比如使用 canvas 绘制动画，读取 DOM 上的 dataset 属性等操作，虚拟 DOM 是不支持的。
2. 如果说有外部引入的 DOM 操作，比如说使用插入一个新的 div，虚拟 DOM 是无法检测到的，需要在操作后调用框架 API 手动通知。
3. 运行时和内存开销：相对直接操作 DOM，虚拟 DOM 实际上相当于引入了一个镜像，只是这个镜像占用的内存稍微小一点。同时在一次加载大量 DOM 的时候，虚拟 DOM 需要处理的内容较多，也会降低峰值性能。
## 如果不使用虚拟 DOM，还有哪些替代方案？
- 如果说运行时不使用，可以用 svelte 等预编译的框架。
- 如果说开发时也不使用，直接上模板引擎（比如 handlebar），或者直接操作 DOM 的框架和原生操作
