### ISSUE TITLE
要入职外包吗？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#48]
### 发生问题的场景

小明的学历一般，但工作能力还行，当前薪酬13k。最近拿到一家外包公司`offer`，薪酬开到20k。

面试过程很简单，一面问了基础和项目，二面就简单聊了下接下来的工作。

### 需要解决的问题

请从以下角度帮小明分析要不要接这个`offer`：

- 外包的职业发展前景

- 外包的晋升路径

- 进了外包，再找工作会受到歧视么？

### 最佳答案评选标准

1. 按以上角度回答问题

2. 有自身切实经历是加分项

## 最佳答案

[lkzwc的回答](https://github.com/BetaSu/fe-hunter/issues/48#issuecomment-1092633407)

另外，[这篇文章](https://github.com/BetaSu/fe-hunter/issues/48#issuecomment-1091104453)很值得参考阅读

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是问题发布24小时后评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by zxytt** [comment]
首先我个人是在一家大厂做外包，工作3年，入行即将满一年，我来外包的原因是：就是想看看大厂都在做什么，小组是新业务线，两个web端，另一个是校招生，我觉得我运气还是挺好的，虽然我是外包，但我是项目的主R，负责核心功能开发迭代；
1.我个人还是不建议去外包的，想通过大厂外包转为正式员工是可以的，毕竟是少数，外包干的都是正式员工分的任务，使用技术单一，对于刚毕业的想快速提升去还是可以的，工作几年的就别去了，努努力，背背八股文，包装下项目也能拿到不错的薪资（找卡子哥）
2.外包还有晋升吗？
3.做外包的出去找工作肯定会受歧视，行业规则吧
如果想躺平些，觉得20k在周围算较高的水平，自己难达到，我认为可以选择

**Comment by claviering** [comment]
为了能有一口饭，什么工作不做？送外卖我也去

**Comment by zhang-chen6** [comment]
@claviering 说的对啊，虽然入职外包有一些弊端，但是为了生活，也能将就过度一些困难的时光

**Comment by fxwing** [comment]
```js
// 为了挣钱  吃屎我也干
```

**Comment by yyyangte** [comment]
https://mp.weixin.qq.com/s/IPNeeu7GRmhq8OmZGswg0g

最近刚看到的一篇文章，大家可以看下

**Comment by song-pan** [comment]
确实会被歧视  会被那些正式工歧视 很恶心 假如你不在乎这些去外包没关系  别以为没有这种恶心的人 这种人很多很多

**Comment by carl-zp** [comment]
第一点从年龄的角度来谈这个：
1、如果你还年轻比如二十四五左右，我认为没有关系，毕竟给的薪资还算到位
2、如果你不年轻了快三十，那我觉得没必要，你必须的为了后续的工作积累一定资源
第二点从技术成长来讲：
去外包无外乎就是很偏业务的东西并且还是一些无关竟要的东西，因为没有任何一家公司的核心业务会放心给外包人员去做。你的技术在工作中几乎不会有什么成长，更别说职业晋升之类的了
第三点从是否存在歧视：
这点还是的看个人吧，林子大了啥鸟都有的。不过有点确实挺恶心的，你在外包公司的权限少之又少，到处受限制

**Comment by HelloXZX** [comment]
> 外包的职业发展前景
如果是包项目的话，可以看公司和项目自己对比。如果是是排外驻到其他公司直接拒绝。

> 外包的晋升路径
这个不同公司是有区别的。不过转到甲方是不错的选择。

> 进了外包，再找工作会受到歧视么
有的公司是会歧视的，虽然可能没那么明显。

**Comment by NoBey** [comment]
thoughtworks 也是外包, 软件咨询市场可不小.

**Comment by SHpoi** [comment]
如果只是恰钱的话，选择一家工资还高的工作就行，不必太纠结于外包。
但如果考虑程序员的职业生涯，想要有所突破的话，还是建议成为正式员工。

下面经历我经历过，可以参考下：
1.工作繁忙，而且不会是核心的活，在外包能干活都已经很累了，一般人很难有精力再去成长
2.除了干活，基本被排除在公司之外，五险一金交的公司不一样吧，年终奖也不是公司发的，是外包公司发的，节假日福利很有可能一些礼品都没你份。一般公司年会是会让外包参与，但抽奖没你份，只有正式员工有。一句话，一般公司员工不会歧视外包，但制度上处处不平等。
3. 外包晋升正式员工的机会，真的很难，不想相信hr入职说的满一年转正，真实情况就是僧多肉少，好几个人抢一个岗位。这还不止，团队内有竞争，团队外也有，不同团队之间也会强正式名额，要是团队kpi不过关，你懂的。相比之下，社招简直太好了，只要能面进去，就能拿到正式岗位，是不是很舒服。
4. 在职业生涯发展中，外包其实对人的伤害挺大的，这个位置太容易产生惰性，这个就不详细说了

总之能不选就别选，除非诱惑太大，但能拿到好点的外包职位，换一家其他公司正式岗位不是随便拿嘛

**Comment by lkzwc** [comment]
首先说下 我本人就在外包公司 ，做的事阿里线，当时入职主要是图钱了，接着我们从各个方面谈谈，首先说说题主关心的

## 外包的职业发展前景
职业发展这个怎么说呢，如果公司好点，内部还有一些技术交流分享，或者一些大牛带带你，如果氛围不好，几乎没人和你说话，如果你不主动的话，大家都是耳机一戴，和甲方巴拉巴拉一沟通，蒙头干活，到点下班。另外说说甲方这边，基本管控很严格，技术交流的什么封锁的比较严格，要想成长太难，总之一句话，全靠自己，如果你自己放松了，那就是温水煮青蛙，如果你自己不放松，那也有的一博，比较薪资可观！

## 外包的晋升路径
几乎没有
* 外包公司层面：基本一个萝卜一个坑，而且干外包的人太多，外包公司这边的管理层面的人数不会太多，而且先入坑为主，后来者基本凉凉
* 再说说甲方这边的，只会给你来来回回画饼，心有多大，饼有多大，一直画饼，从不实践，要想转到甲方感觉你的逼他们更加优秀才有可能会考虑

## 进了外包，再找工作会受到歧视么？
个人感觉肯定会有影响，大多数人对外包的印象都不好，都是简单工作，没什么技术含量，当然这些我感觉还事看个人了，如果你能里出众，即使外包，也会让你成长起来！

# 聊聊其他的
## 工作如何，轻松吗？
> 这个看项目，我们这边基本都是一个人一个项目，很少好几个人挤一起，即使在一起，业务方向也不同的,我这边的话感觉的挺轻松，到点下班，基本有活的时候比较忙，做完了就闲起来了，有时候一周没活的时候头疼周报不知道咋写。当然也有的项目比较紧张，短期内要上线，那就有可能比较忙了！

## 关于加班
> 本来加班有加班费，结果有额度，超过额度要调休，但是基本来没加过班，下班点大家都走了

## 关于技术交流
> 这里可以接触到阿里的一些大佬，偶尔一两周也有技术交流，奈何讲了咱听不懂哈哈

## 值得一提
> 进大厂外包，最直观的感受就是太卷了，不创新，一个项目感觉好几个项目组都在干，而且干的都差不多。不过在怎么迷糊，你可以了解到大厂的方向以及行业的方向，这个是没啥问题的！

**Comment by wood3n** [comment]
不知道国内技术氛围为什么存在这么强的鄙视链，高学历鄙视低学历，后端鄙视前端，同行鄙视外包同行。有些云外包从来都没进过外包，就一天到晚张口闭口外包这不好那不好的，然而呢，自己高不成低不就，总是觉得自己很了不起，半瓶子水晃荡。当然了，您要是年薪百万，就当我放屁😋
