### ISSUE TITLE
实现字符串reverse方法

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#49]
### 要实现的功能

在 JS 中反转一个字符串，你有几种方法？

### 代码示例

```js
function reverseStr(str: string): string {
  // ...实现
}

// 输入字符串: 'Hello World!'
reverseStr('Hello World!')
// 输出: '!dlroW olleH'
```

### 最佳答案评选标准

 

1. 请写出实现思路、代码，并为代码的关键步骤增写注释
2. 不需要考虑异常发生
3. 附带测试用例、多种实现方式是加分项
4. 不过度设计，代码简洁优雅是加分项

## 最佳答案

[virgo569157的回答](https://github.com/BetaSu/fe-hunter/issues/49#issuecomment-1090972161)

### 答题同学须知

- 答题规范：请在`一次评论`中完成作答，后续修改也请编辑该评论，而不是追加新的评论

- 评选标准：最佳答案由`围观同学`的 👍 和[卡颂](https://github.com/BetaSu)共同决定

- 评选时间：一般是问题发布24小时后评选，如果问题发布当天回答数较少，问题悬赏金额可能增加，同时悬赏时间也会增加

### 围观同学须知

- 对于你满意的答案，请不要吝惜你的 👍，这是评选**最佳答案**的依据

- `非答题的评论`会被删除，问题相关讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)中进行

**Comment by xianguoGou** [comment]
方法一：利用数组和字符串原型上的属性就能实现：

```js
const reverseStr = str  =>  str.split('').reverse().join('');

reverseStr('Hello World!')
// 输出: '!dlroW olleH'
```

方法二：使用递归和字符串截取也能实现：

```js
const reverseStr = str => str === "" ? "" : reverseStr(str.substr(1)) + str.charAt(0)
reverseStr('Hello World!')
// 输出: '!dlroW olleH'
```

方法三：使用for循环遍历：
```js
const reverseStr = str => {
    let resultStr = "";
    for (let i = str.length - 1; i >= 0; i--) {
        resultStr += str[i];
    }
    return resultStr;
}
reverseStr('Hello World!')
// 输出: '!dlroW olleH'
```

**Comment by wolfdu** [comment]
```
function reverseStr(str) {
  let left = 0;
  let right = str.length - 1;
  let strArr = str.split('');
  while(left < right) {
    [strArr[left], strArr[right]] = [strArr[right], strArr[left]];
    left++;
    right--;
  }
  return strArr.join('');
}

// 输入字符串: 'Hello World!'
let res = reverseStr('Hello World!')
console.log(res);
// 输出: '!dlroW olleH'

let res1 = reverseStr('Hello World!~')
console.log(res1);
// 输出: '~!dlroW olleH'
```

**Comment by fxwing** [comment]
```js
const reverseStr = (str) =>
  str.length === 0 ? "" : reverseStr(str.slice(1)) + str.charAt(0);
console.log(reverseStr("Hello World!"));
```

**Comment by canvascat** [comment]
参考以上，加上Unicode支持

- Array.prototype.reverse
```js
function reverseStr(str) {
  return Array.from(str).reverse().join('')
}
```

- 循环
```js
function reverseStr(str) {
  let result = ''
  for (let name of str) {
    result = name + result
  }
  return result
}
```

- 双指针
```js
function reverseStr(str) {
  const strArr = Array.from(str)
  let left = 0, right = strArr.length - 1
  while(left < right) {
    [strArr[left], strArr[right]] = [strArr[right], strArr[left]]
    left++
    right--
  }
  return strArr.join('')
}
```

**Comment by carl-zp** [comment]
1. 使用内置方法反转字符串
 function reverseString(str) {
    return str.split('').reverse().join('');
}
reverseString('hello');
2. 用递减的 for 循环反转字符串
function reverseString(str) {
    // Step 1. 创建一个空字符串，用来存储后面新创建的字符串
    var newString = '';

    // Step 2.创建for循环
    /* 循环的起点是（str.length-1），它对应于
        字符串的最后一个字符“o”
        只要i大于或等于0，循环就会继续
        每次迭代后递减i */
    for (var i = str.length - 1; i >= 0; i--) {
        newString += str[i]; // or newString = newString + str[i];
    }
    /* "hello"的length等于 5
        每次循环的公式: i = str.length - 1 and newString = newString + str[i]
        第一次循环:   i = 5 - 1 = 4,         newString = "" + "o" = "o"
        第二次循环:   i = 4 - 1 = 3,         newString = "o" + "l" = "ol"
        第三次循环:   i = 3 - 1 = 2,         newString = "ol" + "l" = "oll"
        第四次循环:   i = 2 - 1 = 1,         newString = "oll" + "e" = "olle"
        第五次循环:   i = 1 - 1 = 0,         newString = "olle" + "h" = "olleh"
    结束for循环*/

    // Step 3. 返回已翻转的字符串
    return newString; // "olleh"
}

reverseString('hello');

3. 用递归反转字符串
 function reverseString(str) {
    return str === '' ? '' : reverseString(str.substr(1)) + str.charAt(0);
}
reverseString('hello');

**Comment by RandyForest** [comment]
使用`Array#reduce()`方法
```ts
function reverseStr(str: string): string {
  return Array.from(str).reduce((a,b)=>b+a)
}
```

**Comment by RJM1996** [comment]
## 反转字符串

### 一、数组反转

```js
const reverseStr = str => str.split('').reverse().join('')
```



### 二、递归

```js
const reverseStr = (str) => (str !== '' ? reverseStr(str.substr(1)) + str.charAt(0) : '')

console.log(reverseStr('hello, world !')) // ! dlrow ,olleh
```



### 三、循环遍历

```js
function test02() {
  const reverseStr = (str) => {
    let resultStr = ''
    for (let i = str.length - 1; i >= 0; i--) {
      resultStr += str[i]
    }
    return resultStr
  }
  console.log(reverseStr('hello, world !'))
}
test02()
```

### 四、双指针

```js
  const reverseStr = (str) => {
    const strArr = str.split('')
    let left = 0
    let right = strArr.length - 1
    while (left < right) {
      ;[strArr[left], strArr[right]] = [strArr[right], strArr[left]]
      left++, right--
    }
    return strArr.join('')
  }
```



### 五、使用栈

```js
  const reverseStr = (str) => {
    const stk = []
    str.split('').forEach((c) => stk.push(c))
    let res = ''
    while (stk.length) {
      res += stk.pop()
    }
    return res
  }
  
  console.log(reverseStr('hello')) // olleh
```

**Comment by shenghui-shan** [comment]
var a = '123456';
var res =  [...a].reduce((pre,cur)=>cur+pre);
console.log(res); // "654321"

**Comment by shenghui-shan** [comment]
var a = '123456';
var res = [...a].reduceRight((pre,cur)=>pre+cur);
console.log(res); // "654321"
