### ISSUE TITLE
如何应对产品经理中途改需求？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#5]
## 问题描述

与你对接项目的产品经理很有自己的想法，`需求评审`敲定方案后，在你开发中途他经常以`当面口述`的方式找你`改需求`。为了保证上线时间不推迟，你被迫熬夜加班。请从以下顺序回答该问题：

1. 是什么导致你加班？
2. 如何`专业的`（不抖机灵，不情绪化）解决这个问题，请详述你的解决步骤？
3. 解决方案如何固化成`正式工作流程`，防止后续再发生这样的事？

## 最佳答案

[jerry-lllman的回答](https://github.com/BetaSu/fe-hunter/issues/5#issuecomment-1075837275)

### 答题同学须知

最佳答案由`围观同学`的`👍`和[卡颂](https://github.com/BetaSu)共同决定。**非答题相关评论**会被删除，问题相关内容讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)里讨论

### 围观同学须知

对于你满意的答案，请不要吝惜你的`👍`，这是评选**最佳答案**的标准

**Comment by ZHENGGEGE** [comment]
1.导致加班的原因是无脑妥协，牺牲开发的时间为产品兜底，但却带来了延期的风险
2.接到产品改需求的详细内容，首先评估方案改动涉及的工作量，如果工作量不大，不影响排期，可以达成一致，确定后通知相关合作方；如果工作量大，则要走需求变更流程，重新评估排期时间，触发排期变更并通知所有合作方、PM
3.修改需求的情况需要落地规范，小改动有对应的流程，大改动有风险的也有相关的需求变更流程，PM角度需要收集日常需求变更、排期变更的case，定期复盘，避免后续出现类似问题

**Comment by BlockHand** [comment]
对于这个问题我经常遇到下面列举几个我平时的应对方法
1、在需求评审完之后我们会敲定，并且出一份最终的需求文档以便日后扯皮
2、在需求确定后给出排期，并且和各个端。（服务端，测试，产品）。同步好并且大家都将自己的排期发出来由测试统一汇总
3、期间如果产品有新的改动点，拉上测试，服务端一起。切记不要自己去应对，要让所有端都知道需求变更。切记(不要自己一个人和产品确认修改后的方案，不要自己一个人和产品确认修改后的方案，不要自己一个人和产品确认修改后的方案)重要的事情说三遍。
4、一旦有了新的方案就重新排期，不要问为什么，因为时间是你自己的。因为产品变更需求导致项目延期你自己扛下来那就是你自己的问题了。坚持自己的想法，一旦变更需求影响开发进度就重新排期
5、最重要的一点，需求变更后一定要让产品修改需求文档，他不修改就不做改动点。因为他如果不修改，你做了以后有问题扯皮全都是你的锅。任何需求对接，都要留有文字性证据。

**Comment by cloudflypeng** [comment]
1,导致加班的原因是产品觉得你的开发是线性的,且产品对功能修改的复杂度没有预估,但是现实开发的时候是阶段性的,经常是某些地方进展慢,有些地方很快就做完了
2.按照紧急与重要程度划分,对于两小时以内且对产品有价值的修改尽量做(但是要在周报里面反映出来),大于半天的就要找leader之间对接.做不做不是最主要的,主要问题是责任人的确认,在项目管理软件上,让产品描述清楚需求修改方式,然后你要加一个评论表示你对于这个问题的看法和大致预期,做好了这个只要安心甩锅就好了
3.我们可以改变自己但是改变不了别人,自己做的没问题老大是不会眼瞎的,也不要企图能改变sb产品做事情的方式,有人意识不到自己有问题

**Comment by bestvayne** [comment]
当然可以改需求了，市场在变，环境在变，需求也有可能会改变。
正确看待问题，首先邮件抄送双方领导，表示收到了更改需求的这个通知，然后告知现在目前项目开发进度。
表示希望可能两边坐下来探讨一下更改这个需求的可能性，如果一定要改，告知对方负责人，我们这边需要对需求进行评审，更高需求需要花费的时间、人力、协调资源花费的时间成本。最后总结一下，然后告诉对方部门这个需求如果真的需求修改的话，前期的一些工作的沉没成本。

叭叭叭的讲完一堆，估计最后就不改了（狗头

**Comment by jerry-lllman** [comment]
首先，这个问题非常的好，程序员老实人太多了，作为老实人之一，聊一下我遇到这样的情况如何应对。
一. 是什么导致你加班？
1. 首先不得不说加班的原因是因为你工作方式的问题，**产品经理不是你的领导，请谨记这一条**，安排来的需求不是非做不可。
2. 导致加班的第二个原因是你太过于高看了产品经理，他出的需求就真的是正确的吗？你有好好参与讨论嘛？你有站在业务的角度去考虑去分析需求嘛？代码写的再怎么牛逼，不去考虑业务，该加班，你就得加班，所以，是你该！！！
3. 第三个原因在于你自己，你太高看自己的技术了。xd，拜托，你的时间你真的能保证100%的利用率吗？求求了，你不摸🐟？不搞搞学习？不上网冲浪，聊聊plmm/sqgg？

二、如何专业的（不抖机灵，不情绪化）解决这个问题，请详述你的解决步骤？
1. 你可以**选择拒绝**，他的需求可能不合理。
2. 拉上一大帮子人去讨论，这个需求值不值得修改，如果讨论的稍微有一点点久了，你可以找更多的人来参与讨论（不限于你们组），这样当他们讨论的眉飞色舞，唾沫横飞的时候，而你，就在一旁做局外人：哎，我觉得李总说的好，哎，王总也说的也有道理，要不然我们再把张总他们组也拉过来再讨论讨论？于是时间都在讨论上了，而你在划水，眼看着讨论的差不多了，你表示，哎，这个上线时间太紧迫了，要不然我们先上线吧（或者我们再重新排一下期吧，这个这么大的改动，这做不完的）。当然，上面那些说的可能没法在每个公司实现，但是讨论讨论还是有的吧，你可以说，**马上要上线了，这功能肯定做不完的，到时候我们几个人不好给老总交代啊**/**我们这个产品还要不要按照规定时间上线了？**（我们是一个利益共同体啊，喂，绩效还要不要了？）
3. 如果真的要改需求（否认了上面的两种方案，毕竟项目活着，你才可能会有好下场），首先要做的就是先自己仔细考虑一下这个需求的可行性，能否做到，需要花多少时间，需要哪些人进行打配合。考虑好了以后，如果产品给的方案不完善，先让他完善，接着就拉上相关人员进行开会讨论，确定需求，重新排期（真的很重要！！！做人厚脸皮一点好不好，自己不好说，让自己TL说啊。什么？TL都不愿意说，你还跟他混个屁啊，赶紧提桶🪣吧）。

三、解决方案如何固化成正式工作流程，防止后续再发生这样的事？
1. 首先，这样的事情多发生几次，先尝试出最佳方案
2. 找自己的TL聊：我们要将这些都流程化，巴拉巴拉，
3. 根据最佳流程制定出执行方案来，给TL看看，有什么点要优化的就让他帮你优化。
4. 接着让TL将这套执行方案向上反馈，一定要找到说话算数的人，自己要多跟进这件事情。

总结一下：程序员，不要老想着自己的代码一亩三分地，代码是为了业务赋能，业务是养活自己的，工作是为了让自己能活下去。**我们普通人不可能只靠牛逼的代码活下去，会做人，才是硬道理**。

写完了，看了下有部分同学写的也不错 👍

**Comment by yearth** [comment]
首先 [jerry-lllman](https://github.com/BetaSu/fe-hunter/issues/5#issuecomment-1075837275) 同学的回答是我最认可的，然后简单聊聊自己的经验。

### 为什么会加班？

我认为这个其实在问题里已经说的很明确了，明明是 `评审敲定` 后， `口头上要求改需求`，已经明示暗示，这个动作不合理，不应该接受。
是否有特殊情况？肯定有的，那需要具体问题具体讨论：
- 是否需要排期加时间？
- 是否真的很紧急？
- 是否真么那么具有业务价值？（关于程序员于业务，我个人理解一向是，作为在车间拧螺丝的员工，如果知道车间是怎么运作的，会更有机会成为车间经理，再不济，工厂不景气的时候，也知道怎么更有效的规避裁员的命运）
- ......

如果这些都不讨论，项目经理说改就改，那么在任何团队可能都避免不了加班的命运

### 另一个问题

与这个问题类似的场景还有，面对后端频繁的甩锅，怎么办？

首先要明确一点，大家在一起是做事的，不可避免的会出现问题，当遇到问题，重要的不是分锅，而是搞清楚问题是怎么来的，如何解决，未来能否有效的规避？

至于怎么办，个人的经验是，无论是评审会，静态页面研发完成还是联调完成的节点上，都在群里同步 PD，Owner 等，完成一个 check 的动作，一定要是群里，群里的消息自带一定的公证性。

**千万不要私聊，千万不要私聊，千万不要私聊！**

### 再补充一个视角

即使不考虑个人感受，从公司角度出发，长期因为不规范的行为导致开发疯狂加班，也是不利的。
公司，团队，需要稳定，而如果某一个人长期在高压环境下，那他就是不稳定的，代码出现 bug 的概率更高，而这个人受不了这个环境离开之后，能否有人快速顶上去，顶上去之后面对前人因为高压而留下来的屎山，并且同样是高压环境，又能抗多久？
那么当这个岗位变得不稳定之后，项目能否稳定，产品能否稳定，团队又能否稳定呢？

**Comment by jerry-lllman** [comment]
> 首先 [jerry-lllman](https://github.com/BetaSu/fe-hunter/issues/5#issuecomment-1075837275) 同学的回答是我最认可的，然后简单聊聊自己的经验。
> 
> ### 为什么会加班？
> 我认为这个其实在问题里已经说的很明确了，明明是 `评审敲定` 后， `口头上要求改需求`，已经明示暗示，这个动作不合理，不应该接受。 是否有特殊情况？肯定有的，那需要具体问题具体讨论：
> 
> * 是否需要排期加时间？
> * 是否真的很紧急？
> * 是否真么那么具有业务价值？（关于程序员于业务，我个人理解一向是，作为在车间拧螺丝的员工，如果知道车间是怎么运作的，会更有机会成为车间经理，再不济，工厂不景气的时候，也知道怎么更有效的规避裁员的命运）
> * ......
> 
> 如果这些都不讨论，项目经理说改就改，那么在任何团队可能都避免不了加班的命运
> 
> ### 另一个问题
> 与这个问题类似的场景还有，面对后端频繁的甩锅，怎么办？
> 
> 首先要明确一点，大家在一起是做事的，不可避免的会出现问题，当遇到问题，重要的不是分锅，而是搞清楚问题是怎么来的，如何解决，未来能否有效的规避？
> 
> 至于怎么办，个人的经验是，无论是评审会，静态页面研发完成还是联调完成的节点上，都在群里同步 PD，Owner 等，完成一个 check 的动作，一定要是群里，群里的消息自带一定的公证性。
> 
> **千万不要私聊，千万不要私聊，千万不要私聊！**
> 
> ### 再补充一个视角
> 即使不考虑个人感受，从公司角度出发，长期因为不规范的行为导致开发疯狂加班，也是不利的。 公司，团队，需要稳定，而如果某一个人长期在高压环境下，那他就是不稳定的，代码出现 bug 的概率更高，而这个人受不了这个环境离开之后，能否有人快速顶上去，顶上去之后面对前人因为高压而留下来的屎山，并且同样是高压环境，又能抗多久？ 那么当这个岗位变得不稳定之后，项目能否稳定，产品能否稳定，团队又能否稳定呢？

感谢认可，补充的很nice，另外我认为如果公司不认可，我也觉得没有继续待下去的必要了，毕竟良禽择木而栖。
PS：我好像一肚子坏水儿似的😂

**Comment by liuxiansheng2018** [comment]
首先我们来分析需求评审敲定之后， 在开发途中以口述的形式进行分析
1. 针对与任何改需求的操作都会碰到，当时任何不能以口头的形式告知， 而是在对应的prd上有所变更，进行标识， 在群里通知对应的测试，整个团队开发人员， 需求的变动是否会影响当前的排期， 技术方案， 影响点都是要进行考虑。
2. 如果针对与一些文案的改动，样式简略的变更， 在不影响排期的情况下，如果达成一致则需要告知合作方， 
3. 其次我们还要分析这个开发途中是在到了什么阶段， 假设在刚刚开始开发的时候提出来， 需求改动与技术方案冲突较大，那则需要相关开发同学， 项目经理，测试同时在场， 重新评估技术方案， 修改排期时间，如果在排期不能改变的情况下直接拒绝当前产品的问题， 并指明由于如果新增需求的话则会导致项目延期
4. 其次还是要看这个需求做不做， 或者放到下次做价值有多， 是不是非这次不可

**Comment by ghost** [comment]
> 无论是评审会，静态页面研发完成还是联调完成的节点上，都在群里同步 PD，Owner 等，完成一个 check 的动作，一定要是群里，群里的消息自带一定的公证性。

> **千万不要私聊，千万不要私聊，千万不要私聊！**


不要私聊这个太正确了，因为产品经理可能会不认账……

可能有这样一种情况：你在和产品经理私聊的过程中，他表现出同意你的观点，但是在和领导汇报的时候，他会不承认你之前得出的结论，导致你做了无用功。

之前朋友遇到的产品就会这样。

在群里发出来 check，可以 **保护自己**。

**Comment by tunshiyu** [comment]
关于事的事情可以用方法论，关于人的事情不可。
