### ISSUE TITLE
如何选择前端打包工具？

### ISSUE THREAD

**Issue by BetaSu** [BetaSu/fe-hunter#9]
## 问题描述

当前市面上有很多前端打包工具，比如：

- webpack
- rollup
- vite
- parcel
- browserify

他们各有侧重，又有功能交集。当你在搭建一个新项目时，该如何选择打包工具呢？可以从以下方面回答：

- 打包工具适合的业务场景？
- 打包工具社区生态是否丰富？
- 打包工具的可扩展性？
- 打包工具的上手难度
- ......

## 最佳答案

[XeryYue的回答](https://github.com/BetaSu/fe-hunter/issues/9#issuecomment-1077019965)

### 答题同学须知

最佳答案由`围观同学`的`👍`和[卡颂](https://github.com/BetaSu)共同决定。**非答题相关评论**会被删除，问题相关内容讨论请在[赏金猎人群](https://github.com/BetaSu/fe-hunter)里讨论

### 围观同学须知

对于你满意的答案，请不要吝惜你的`👍`，这是评选**最佳答案**的标准

**Comment by nonzzz** [comment]
关于打包这个问题是一个很有考究的学问,不论是`bundle`还是`transform`,存在即合理。这里我会以我个人的经历浅谈如何选择打包工具链。

### 明确工程场景

在后续选择打包工具之前,我们应该先思考的是我们的工程服务的群体是什么样的,是类库还是应用工程。先想明白服务群体才能更好的选择工具。这里先给出我自己的结论如果不是应用工程大可不比`bundle`而是选择`transform`。关于这点我会在后续的部分进行详细展开。


### 组件类库的选择

这里我们以类库方向的工程进行切入点,在搭建一个类库工程 `gulp`+`babel`是一个很好的解决方案。一个负责对`disk`进行`IO`,一个负责`transform`然后把结果给`gulp`进行输出。我们可以观看很多大型lib都是采取这么一个模式。在现代的工程我们不需要对一个类库进行打包因为打包以后在使用你会面临着二次打包,这一点我们从无数组件库便可窥得一二。因为在使用的时候我们往往是引入对应的组件部分而不是整个`entry`。所以`transform`的使用场景基本集中于此。那么不是组件库的库我们该怎么做？这里就以我在维护的`h265webjs`举例[项目地址](https://github.com/numberwolf/h265web.js), 因为这个项目足够小它不需要`webpack`这样的重型工具，`browserify`提供的模块功能足够我们使用。因此我们就会使用他。

### 其他类库的选择

相较于`babel`，`swc`,`tsc`+ 磁盘IO的操作,有些时候我们不约而同的看到了`rollup`+`api-extractor`的组合方案，这里以我个人角度来看,这些往往适合于纯`js`的库。比如`vue`。我们先看`rollup`的描述将无数小的模块聚合成一个大的模块。那么在这些大型`js`
库往往需要把这些模块整合方便输出不同环境下的包,这点是纯`transform`所做不到的,具体的最佳实践我们可以看看vue,出色的利用了`rollup`完成不同模式的打包。

### 应用工程

说完了类库的选择，就剩下了工程相关的了。关于`vite`,`webpack`,`parcel`都是作为一些上层解决方案这里给出我的经验,现阶段除了`webpack`都不靠谱。`vite`给我最大的感受就是缝合了`rollup`但是顺带把`rollup`的bug也一起缝进来了。这种强依赖于上游的包。在面对复杂的前端应用工程往往无法面面俱到。因此我们看到了在面对低版本兼容的需求下`vite`是无法升任的。这一点也和`rollup`有关系。因为`rollup`在设计之初就不是为`web`应用开发服务的。反观`webpack`这种虽然大但是在面对复杂的场景他是游刃有余的。无论是从社区生态还是近乎完美的打包支持webpack占据着绝对的地位。`webpack`的抽象程度之所以复杂是因为承担的场景不是其他的打包工具能比拟的这一点也是经常被人诟病,但是推倒重来我们真的可以做得更好吗？再谈谈新晋的宠儿`parcel`。我有幸使用过一次给我的感觉也是和`vite`差不多也不再展开。
至于已经死去的`snowPack` 大概是我对`bundleless`的最后一丝幻想了吧。

**Comment by coconilu** [comment]
非跨端项目，我推荐vite。

它由no-bundler开发服务器和rollup bundler两部分组成。

vite可以给开发者带来极速的开发体验，借助rollup成熟的插件生态可以输出符合生产环境的产物。

跨端项目的话，目前是webpack比较成熟，速度是慢了点，聊胜于无，期待下一款跨端vite生产工具的诞生。

**Comment by songjingwei** [comment]
我只用过 webpack，组里项目直接 vue-cli😓。

**Comment by ygh1** [comment]
简单项目不想累，快速的话，用parcel，开发的库选择 rollup，因为不包含多余的代码，如果目前一般传统项目，还是用webpack，尝尝鲜用 es-build

**Comment by sdta25196** [comment]
上班不能摸鱼，时间紧，快点说
写类库 打包用rollup
写应用打包用webpack
不考虑兼容性用vite
其实ts的东西，直接tsc也挺好
snowPack 、swc、parcel等等等这些，学太多容易把自己累死。

补一下。选类库要看你项目大小、工程体系、面向的对象、使用的语言、甚至还有你团队的技术栈，你的剩余时间这些东西综合考虑的。不能一概而论。

**Comment by wood3n** [comment]
对于 TypeScript 编写的类库来说，使用`rollup` + `api-extractor` 肯定是最佳实践，`rollup`负责构建生成 JS 文件，`api-extractor`负责汇总`.d.ts`文件，`vite`就是这么干的。

**Comment by nonzzz** [comment]
> 对于 TypeScript 编写的类库来说，使用`rollup` + `api-extractor` 肯定是最佳实践，`rollup`负责构建生成 JS 文件，`api-extractor`负责汇总`.d.ts`文件，`vite`就是这么干的。

`api-extractor`是要看具体场景的。不是每个都适用,例如组件库这样的类型他是不适合的
